ARM-software/SCP-firmware

framework/src/fwk_assert.c, framework/src/fwk_dlist.c, framework/src/fwk_slist.c, product/sgm775/scp_romfw/config_sds.c, tools/build_system/doc.md, tools/build_system/rules.mk, tools/build_system/test.mk
Renamed as all symbols/define exposed by the build system should
have the prefix BUILD_ in their names.
Change-Id: I8893121b32c31584a163a991547925cc028ee1c9
=> bs: Rename MODE_DEBUG to BUILD_MODE_DEBUG

module/timer/include/mod_timer.h, module/timer/src/mod_timer.c
When an alarm is triggered a callback function is called instead
of sending an event to the module or element that set the alarm.
That way an alarm trigger does not necessarily generate an event
and for example register polling can be done more effectively.
Change-Id: I7ef16976c8f90e3f772ae57056f5891636533170
Signed-off-by: Elieva Pignat <Elieva.Pignat@arm.com>
=> timer: alarm triggers a callback function

module/pik_clock/include/mod_pik_clock.h, module/pik_clock/src/mod_pik_clock.c
PIK clock divider value limit checking is hardcoded to 16 with
4-bit assumption. However many mobile & infra platforms has
5-bit divider.
This patch fixes the issue by adding a configurable module parameter
so that the platform's config file can set the divider bitfield size
based on platform.
Additionally, if platform does not provide module configuration data,
then the divider limit is set to a default value of 5-bits.
Change-Id: I70103ec84eacc2d26be999ca6524878bff51dd9d
=> pik_clock: make divider value check limit as configurable parameter

framework/src/fwk_dlist.c, framework/test/test_fwk_list_pop.c
If a dlist contained more than two nodes, the previous link
of the new list head was not updated and pointed still to the
popped head.
Change-Id: I19507a6910d714f441290db8de5481113847370d
Signed-off-by: Elieva Pignat <Elieva.Pignat@arm.com>
=> dlist: fix pop_head to work for any size dlist

tools/build_system/cpu.mk
CCR.UNALIGN_TRP is enabled, and will trap any unaligned access. We need
to ensure the compiler does not generate them.
Change-Id: Ia0166578c00fa53399aa9823eec8f166b70b0762
=> build: Disable generation of unaligned accesses

module/pik_clock/src/mod_pik_clock.c
This patch fixes compiler warning that arises when building firmware
without css_clock module and with GCC 7 compiler.
Change-Id: I5b55a51ac4de827a2ae7332043efa92edf4853da
=> pik_clock: fix compiler warning when building with GCC-7 compiler

tools/build_system/firmware.mk
Having different file names makes it easier to differentiate
the firmware binaries. It also removes the need for renaming
them when they are placed in a common directory.
The firmware.bin binary file is still generated by the build
system. A subsequent patch will remove its generation giving
time to remove any dependency on it.
Change-Id: Id38c20d667f802f18abf090b0c331b796c2ce23d
=> build: Name firmware bin and elf file by the name of the firmware

product/n1sdp/module/n1sdp_flash/include/internal/n1sdp_flash_layout.h, product/n1sdp/scp_ramfw/config_sds.c, tools/check_style.py, tools/ci.py
Some of the syntax used in N1SDP is incompatible with Arm Compiler 6, including __packed and static_assert (without <fwk_assert.h>).
This commit also adds the relevant missing CI build tests.
=> n1sdp: Fix armclang compilation issues

module/sid/include/mod_sid.h, module/sid/src/mod_sid.c
Remove the need to bind to the sid module interface. This enables access
to the system information data during the initialization stage of the
pre-runtime phase. This way, configuration data can be tuned according
to system information data.
Change-Id: I2e9e37d562af0d7f6a8ba844a79a78f823f6a64a
=> sid: Move to an always available interface

module/cmn600/src/mod_cmn600.c
Registers belonging to external nodes cannot be accessed if the power
domain that the node belongs to is not on. We therefore need to avoid
calling `get_node_type()` on external nodes, as doing so will fail.
Change-Id: Iac405c9f4c7095018cfec79185e6b84dece81e73
=> cmn600: Stop checking type of external nodes

contributing.md, dco.txt, license.md
With this patch, the SCP-firmware will accept contributions to the project
from non-Arm contributors. Contributions must be made under Developer
Certificate of Origin (DCO).
This patch updates the contributing guidelines to describe how contributions
can be made, and additionally adds a copy of the DCO terms.
Change-Id: I1cb23b1785c4fb074ae0c344556319a2d7a0254e
Signed-off-by: David Cunado <david.cunado@arm.com>
=> Opening SCP-firmware to external contributions

product/n1sdp/module/n1sdp_pcie/src/mod_n1sdp_pcie.c, product/n1sdp/module/n1sdp_pcie/src/n1sdp_pcie.c, product/n1sdp/module/n1sdp_pcie/src/n1sdp_pcie.h
This patch adds support for PCIe Gen3 and Gen4.
CCIX supports Gen4 whereas PCIe supports Gen3.
=> n1sdp: Add pcie gen3 and gen4 support

product/n1sdp/module/n1sdp_pcie/src/n1sdp_pcie.h
This patch increases the link training timeout to 100ms such that
PCIe GEN4 cards connected to CCIX slot have sufficient time to
auto negotiate to GEN3 speed.
Change-Id: Ie9ecaed8f754fb664d6e26534fe204fd475d8621
=> n1sdp: increase link training timeout to 100ms

product/n1sdp/module/n1sdp_pcie/src/mod_n1sdp_pcie.c, product/n1sdp/module/n1sdp_pcie/src/n1sdp_pcie.c, product/n1sdp/module/n1sdp_pcie/src/n1sdp_pcie.h
PCIe express extended capabilities like ATS & PRI should be
exposed only in endpoint mode. This patch adds a function to
skip these capabilities in capability linked list for root port
mode.
Change-Id: I2709e39fc7d9f9b4bcfebc67b41d7abe3ec7ab0f
=> n1sdp: add function to skip pcie express capability (ATS & PRI)

product/n1sdp/module/n1sdp_pll/include/internal/n1sdp_pll.h, product/n1sdp/module/n1sdp_pll/include/mod_n1sdp_pll.h, product/n1sdp/module/n1sdp_pll/src/mod_n1sdp_pll.c, product/n1sdp/scp_ramfw/config_n1sdp_pll.c
This patch adds lookup table for frequencies that are not an
integer multiplication of the reference clock.
In such case, n1sdp_pll module sees if a matching frequency is
available in lookup table and uses PLL parameters from the table.
Change-Id: Ic737b3bed17190425064a37a05de5cf35f84dffb
=> n1sdp: add frequency lookup table for n1sdp_pll

module/scmi/src/mod_scmi.c
This patch replaces strcpy for copying literal
Change-Id: I7695cee46958facb79829241b8b4b6f3848adeb1
Signed-off-by: Brett Warren <brett.warren@arm.com>
=> scmi : Replace usage of strcpy

framework/include/fwk_event.h, framework/include/fwk_mm.h, framework/test/test_fwk_mm.c
This commit replaces uses of uintmax_t with max_align_t where the
purpose is to identify the largest possible alignment of any type.
Change-Id: I3be23f36f45a6c9f767314debfe81251abefc78e
=> fwk: Replace base alignment reference type with max_align_t

Makefile, change_log.md, framework/test/test_version.c, readme.md, user_guide.md
Update firmware version to v2.5.0 and update the
documentation for the release of SCP-Firmware v2.5.0
Change-Id: Icd977b1adbffb23c1690387162a21b4266b4ff29
=> Update firmware version to v2.5.0

change_log.md, readme.md, user_guide.md
This commit updates the user guide to bring it in-line with the latest
v2.5.0 release. It changes the Markdown header syntax in order to
represent deeper header levels, replaces old links and attempts to clear
up areas of potential confusion with instructions.
Change-Id: I99b464a4bc94f4618779fbe09b1aa77bed0c318e
=> doc: Update user guide

framework/src/fwk_interrupt.c, framework/test/test_fwk_interrupt.c
Handles global interrupt enable/disable nesting using counter
Change-Id: I2d2da0225f84dfa1e9c270662ea30d13f861323c
Signed-off-by: Brett Warren <brett.warren@arm.com>
=> irq : add handling for nested critical sections

tools/build_system/rules.mk
This commit adds a basic security justification to the Makefile rules,
explaining the reasons for increasing the compiler warnings used.
Change-Id: Id867f90fc88014a1801ca341e6d1c0c75faa0f35
=> bs: Add justification of compiler warning flags

module/scmi/include/internal/scmi_base.h, module/scmi_perf/include/internal/scmi_perf.h
Reemove unnecessary externs from SCMI module internal header files.
Change-Id: I6a74ba18db214b401fb8705606c46b32ead99003
Signed-off-by: Souvik Chakravarty <souvik.chakravarty@arm.com>
=> scmi: Remove unused declarations

arch/src/Makefile, arch/src/armv7-m/exceptions.c, arch/src/armv7-m/exceptions.h, arch/src/armv7-m/handlers.c, product/juno/module/juno_soc_clock/src/mod_juno_soc_clock.c, product/juno/scp_romfw_bypass/firmware.mk, product/juno/scp_romfw_bypass/juno_pll_workaround.c, tools/build_system/rules.mk
The current approach to resetting the PLLs, which is to use a pre-main
constructor function, is not infallible - if we statically allocate
enough data, eventually the time it takes for the C runtime to
initialize exceeds the amount of time that the motherboard
microcontroller gives us to ensure the system PLLs are locked.
The workaround for this is to instead wrap the core's reset handler.
This way we ensure that the PLLs have been reset before we do any time-
consuming work.
=> Ensure system PLLs on Juno are locked within MCC timeout

doc/config.dxy, doc/deferred_response_architecture.md, framework/src/fwk_module.c, framework/test/test_fwk_module.c, module/scmi_sensor/include/internal/scmi_sensor.h, module/scmi_sensor/src/mod_scmi_sensor.c, module/sensor/include/mod_sensor.h, module/sensor/src/mod_sensor.c, module/sensor/src/sensor.h, product/juno/module/juno_adc/include/mod_juno_adc.h, product/juno/module/juno_adc/src/Makefile, product/juno/module/juno_adc/src/juno_adc.h, product/juno/module/juno_adc/src/mod_juno_adc.c, product/juno/module/juno_system/src/mod_juno_system.c, product/juno/module/juno_xrp7724/include/mod_juno_xrp7724.h, product/juno/module/juno_xrp7724/src/mod_juno_xrp7724.c, product/juno/scp_ramfw/config_juno_adc.c, product/juno/scp_ramfw/config_juno_xrp7724.c, product/juno/scp_ramfw/config_juno_xrp7724.h, product/juno/scp_ramfw/config_reg_sensor.c, product/juno/scp_ramfw/config_sensor.c, product/juno/scp_ramfw/config_sensor.h, product/juno/scp_ramfw/firmware.mk, product/n1sdp/scp_ramfw/config_sensor.c, product/rdn1e1/scp_ramfw/config_sensor.c, product/sgi575/scp_ramfw/config_sensor.c, product/sgm775/scp_ramfw/config_sensor.c
This PR:
- Adds documentation explaining  a typical handling of deferred request
- Adds improvements for sensor HAL and scmi_sensor modules for handling pending requests
- Adds support for sensors for the juno board
=> Sensor: Handled deferred request & Add support for juno

module/clock/src/mod_clock.c
Adds explicit casts where compiler reports issues.
Prevents module_ctx variable being exported outside the scope clock
module source file.
Adds braces around a conditioned a multi-line instruction block:
consider inline comment a part of the instruction block.
=> module clock: minor cast, export, braces fixup

product/n1sdp/module/n1sdp_pcie/src/mod_n1sdp_pcie.c, product/n1sdp/module/n1sdp_pcie/src/n1sdp_pcie.c, product/n1sdp/module/n1sdp_pcie/src/n1sdp_pcie.h
This patch adds GEN4 link training support for CCIX root complex
to support GEN4 cards in CCIX slot on N1SDP platform.
Change-Id: I73fc76c1575326017599634747cd15c151f9e08c
=> n1sdp: add GEN4 support for CCIX root complex

product/sgi575/module/sgi575_system/src/mod_sgi575_system.c
SGI-575 platform does not instantiate CPU_PPU_INT_STATUS[7..4]
registers. So remove access to these registers.
Change-Id: I5405bb378f6789bcc1e8470cabbee82c6daa4314
Signed-off-by: Thomas Abraham <thomas.abraham@arm.com>
=> sgi575_system: remove access to CPU_PPU_INT_STATUS[7..4] registers

product/n1sdp/include/n1sdp_sds.h, product/n1sdp/module/n1sdp_system/src/mod_n1sdp_system.c, product/n1sdp/scp_ramfw/config_sds.c
N1SDP can support multichip configuration wherein n1sdp boards are
connected over high speed coherent CCIX link, for now only dual-chip
is supported.
Multichip information can only be probed in SCP, use SDS region to
propagate this information to TF-A.
This patch introduces a new SDS to store multichip information and a
place holder to update this information provided by C2C module which is
responsible for probing chip-to-chip information.
Currently it is configured as single-chip system but once C2C module is
added this information will be filled dynamically.
Change-Id: I57e4aac5c32aa22f927faac4a3f91876ef34dd23
Signed-off-by: Manish Pandey <manish.pandey2@arm.com>
=> n1sdp: introduce multichip information SDS region.

product/n1sdp/include/n1sdp_sds.h, product/n1sdp/module/n1sdp_system/src/mod_n1sdp_system.c, product/n1sdp/scp_ramfw/config_sds.c
Merge mem_info and multichip information into a single data structure
which will be passed on to TF-A.
This patch introduces a new SDS to store platform information, which
will be populated dynamically by SCP.
This structure holds following information:
- multichip_mode
- slave_count
- local_ddr_size
- remote_ddr_size
Change-Id: Ib71c1adabcaff227a22144fdb0b7eea28495cc2b
Signed-off-by: Manish Pandey <manish.pandey2@arm.com>
=> n1sdp: use single SDS for mem_info and multichip info

framework/include/fwk_interrupt.h, framework/include/internal/fwk_interrupt.h, framework/src/fwk_interrupt.c, framework/test/test_fwk_interrupt.c
Add missing declaration of exported function fwk_interrupt_init()
and fwk_interrupt_set_isr_fault().
=> fwk_interrupt: add missing declaration of exported functions

module/mock_psu/include/mod_mock_psu.h, module/mock_psu/src/mod_mock_psu.c, module/psu/include/mod_psu.h, module/psu/src/mod_psu.c, product/rdn1e1/scp_ramfw/config_mock_psu.c, product/sgi575/scp_ramfw/config_mock_psu.c, product/sgm775/scp_ramfw/config_mock_psu.c
This PR enables asynchronous operations at both the HAL and driver level of the `psu` module.
=> Add asynchronous support to the `psu` module

framework/include/fwk_status.h, framework/src/Makefile, framework/src/fwk_status.c, module/log/include/mod_log.h, module/log/src/mod_log.c, module/power_domain/src/mod_power_domain.c, module/scmi/src/mod_scmi.c, module/scmi_power_domain/src/mod_scmi_power_domain.c
Prior this change was %e a valid format for printing error codes as
strings when identified. This change removes such support and replace
use of %e with use of standard format identifier and a error code
to string conversion function.
With this change, any standard printf-like format comply with
SCP-firmware traces implementation. fwk_err2str() helps traces to get
nice string identifier for errors.
=> log: discard non standard %e format

module/scmi_sensor/src/mod_scmi_sensor.c
This patch fixes the status returned to scmi when
the result is provided through a response event. In the
case of a hardware failure, the agent is now correctly
informed of such state.
Change-Id: I96c09e3f63afa86bef64da81da346895ea738f22
=> scmi_sensor: Fix return value from response event

module/dw_apb_i2c/src/mod_dw_apb_i2c.c, module/i2c/doc/module_i2c_architecture.md, module/i2c/include/mod_i2c.h, module/i2c/src/mod_i2c.c, module/scmi_clock/src/mod_scmi_clock.c, product/juno/include/juno_alarm_idx.h, product/juno/module/juno_xrp7724/src/mod_juno_xrp7724.c, product/juno/scp_ramfw/config_timer.c
This PR aims to:
- clean-up & update the i2c module to support sync/async drivers
- fix mistakes for scmi_clock module
- add alarms count for the juno board in preparation for future support
=> I2c and juno misc

module/mock_sensor/include/mod_mock_sensor.h, module/mock_sensor/src/Makefile, module/mock_sensor/src/mod_mock_sensor.c
This patch adds a mocker for sensors.
This module implements the sensor driver API and
defers the get_value requests. This module requires
the timer facilities in order to setup an alarm.
This would emulate a sensor that provides a value
through an ISR and a call to the driver_response API
of the sensor module.
This module can be used to test sensor call flow
in platforms that do not provide asynchronous sensor
drivers.
Change-Id: I37baa428c12d6aa1c3de2f6f534ab5ac158f2352
=> mock_sensor: Add module

contributing.md
Add an explicit statement to the contributors document detailing the
follow-through policies for the contributor and the maintainer.
Change-Id: I57460afdc0c08582f8fef3285414b26543b4c564
=> doc: Clarify contributors' and Maintainers' responsibilities.

module/cmn600/src/mod_cmn600.c
Number of Host RA has been modified to include RN-D's as also
Requesting Agents. Modify the host_ra_count to pass the correct
information for Endpoint programming.
Also, there can be topologies where external RNSAM count is 0.
So remove the check for external_rnsam_count.
=> n1sdp: fix host_ra_count which gets passed to End Point

product/juno/module/juno_ppu/src/mod_juno_ppu.c
This patch removes the trap when attempting to set
the PPU for the DBGSYS to OFF. This allows debugging
SCP to continue.
Change-Id: I3abb69319605cc2fe5766e339e386e01d2207e16
=> juno_ppu: Don't trap when attempt to turn off DBGSYS

doc/code_rules.md
The command described in the documentation reflected the CI and wasn't
adapted for invoking Cppcheck locally.
Change-Id: I307f8f03298049701ce30fd0c129173ce4dc3cd9
=> doc: Correct Cppcheck invocation description

tools/build_system/rules.mk
The Juno ROM is not pressured for size, and a bug in binutils currently
prevents LD from wrapping functions when LTO is enabled.
Change-Id: If0a0f22e22bb96a5a6d07f0fbd3b0ef980c6ea39
=> build: Disable LTO for Juno ROM

module/power_domain/src/mod_power_domain.c
While transitioning a power domain to a particular state, we should not
expect any driver input if the driver has failed to initiate a power
domain transition.
Change-Id: If9b03221b30251f01855e220e5ef2a80f5c7ef80
=> power_domain: Handle power_domain set_state error

product/juno/module/juno_cdcel937/src/mod_juno_cdcel937.c
The first four bytes of the PLL Config register are not used by Juno, so
we always skip them when reading/writing the PLL configuration. The
address was not incremented for the write after a read when setting the
PLL data in set_rate_from_index() call.
Change-Id: I094d3648168a1142cba4ee90e51aa31b3b93de88
=> juno: CDCEL clock driver uses incorrect address for I2C transaction

product/juno/module/juno_cdcel937/src/mod_juno_cdcel937.c
The first four bytes of the PLL Config register are not used by Juno, so
we always skip them when reading/writing the PLL configuration. The
address was not incremented for the write after a read when setting the
PLL data in set_rate_from_index() call.
Change-Id: I094d3648168a1142cba4ee90e51aa31b3b93de88
=> Fix CDCEL Driver

product/n1sdp/module/n1sdp_system/include/mod_n1sdp_system.h, product/n1sdp/module/n1sdp_system/src/mod_n1sdp_system.c
This patch enables non-secure world to access CoreSight debug
address space by configuring the NIC-400 registers.
Change-Id: Ib15868a91c80da54f655aa3f23c35695c9362419
=> n1sdp: enable non-secure coresight debug access

product/juno/include/juno_clock.h, product/juno/scp_ramfw/config_clock.c, product/juno/scp_ramfw/config_juno_cdcel937.c, product/juno/scp_ramfw/config_juno_hdlcd.c
The changes introduced here correct the naming of the two HDLCD clocks exposed through SCMI so that they match expectations.
The binding between the HDLCD driver and the CDCEL driver is also corrected so that the response to events get send correctly back to the client.
=> HDLCD clock fixes

product/juno/scp_ramfw/config_reg_sensor.c
The value read when doing a get_value is 64-bit so we need to store a
64-bit value in the fake register.
Change-Id: I3cf451e2659436106cc93605928fde527045ac23
=> juno/reg_sensor: Change the type of the fake_register to uint64_t

product/juno/scp_ramfw/config_juno_cdcel937.c
This patch is to fix the output identifier for the
two HDLCD logical clocks which are set through the output
Y6 of one of the CDCEL937 drivers available on the board.
Change-Id: Idbec3725a2760eeee211c6c22248d547a73e6794
=> juno/cdcel937: Fix output index for HDLCD0 & 1

doc/code_rules.md
The link pointing to the Cppcheck suppression list used was broken. This
patch corrects it.
Change-Id: Ibb512df1e61f5aa76c56804e13ea368294b0b973
=> doc: Fix link location for Cppcheck suppression list

product/juno/module/juno_cdcel937/src/mod_juno_cdcel937.c
If the preset is not found in the lookup table it is calculated using
the rate in MHz. To avoid floating point arithmetic and the associated
memory cost we will simplify the (rate / MHz) calculation to be a
uint32_t operation.
This results in a memory saving of approximately 1.5kb. As we should
usually get a hit in the lookup table this is an acceptable trade-off.
Change-Id: I2e2a78f85bdb3cd9e35149a324000935d3d8ebb5
=> juno: Convert fp32 to u32 for CDCEL937 calculations

framework/include/fwk_thread.h, framework/src/fwk_thread_delayed_resp.c, module/i2c/doc/module_i2c_architecture.md, module/i2c/src/mod_i2c.c
On a system, it is usual for several I2C slaves to be attached to the same I2C bus. This results in possible concurrent accesses to the I2C bus as a firmware entity may want to access a device it controls through the I2C bus while the bus is busy communicating with another device.
This series adds support for concurrent requests on an I2C bus. That way, users of this module don't have to take into account that they may share an I2C bus.
=> i2c: Add support for concurrent requests

product/n1sdp/module/n1sdp_timer_sync/src/mod_n1sdp_timer_sync.c, product/n1sdp/scp_ramfw/config_n1sdp_timer_sync.c
This patch fixes random boot failures in timer synchronization
between two N1SDP in multichip operation by:
1. Reset the REFCLK counter before starting the sync process.
2. Adjust the CCIX delay close to the board setup.
Change-Id: I3b721a43a68f7ab8695231f8340012122b5f7875
=> n1sdp: fix timer sync random failures in multichip mode

product/juno/module/juno_pvt/src/mod_juno_pvt.c
The status to be returned to the response notification
needs to be assign before the put_event.
This patch fixes this.
Change-Id: Ie517a941b75d5d085247cf245cbeac84b26ae20c
=> juno/pvt: Fix notification response parameter

product/juno/include/juno_alarm_idx.h, product/juno/module/juno_thermal/include/mod_juno_thermal.h, product/juno/module/juno_thermal/src/Makefile, product/juno/module/juno_thermal/src/mod_juno_thermal.c, product/juno/scp_ramfw/config_juno_thermal.c, product/juno/scp_ramfw/config_juno_thermal.h, product/juno/scp_ramfw/firmware.mk
This patch adds a single threshold thermal protection
for the Juno platform. Once the temperature exceeds the
threshold the module will request a forced shutdown.
Change-Id: I4704195e52cdba9f2d94d334e3a347e07c6e0726
=> juno/module: Add thermal protection

module/cmn600/include/internal/cmn600_ccix.h, product/n1sdp/module/n1sdp_pcie/src/n1sdp_pcie.h
Change the CCIX_VENDER_ID to a CCUV value.
Change-Id: I061f7f980c5c1f7f81f484d087ff6d81136b466a
Signed-off-by: Chandni Cherukuri <chandni.cherukuri@arm.com>
=> ccix: change to CCUV

module/cmn600/src/mod_cmn600.c
Host HA count in the CCIX Host configuration data will be passed to the
next stage of bootloader (typically UEFI) to help the CCIX configuration
driver to start assigning the Remote AgentIDs. While calculating the
RN-F count, Host HA count is incorrectly incremented resulting in wrong
assignment of Remote AgentIDs. Due to this Remote RA to Remote HA memory
test failed. Fix this by removing the incorrect increment of Host HA
count while calculating RN-F count. While at it, remove a redundant
comma when displaying the number of nodes discovered.
Change-Id: I2a02035617ed4e0576fb05e41534edbf8e42b0a1
=> cmn600: fix host ha count

product/juno/scp_ramfw/config_juno_pvt.c
With this change the calibration values are correctly
set based on the board version.
Change-Id: Iaf1aff54183be0110713d66f06ee23cfa8f7eb12
=> juno/pvt: Use correct calibration for SoC temp

module/dvfs/src/mod_dvfs.c
FWK_PENDING should be returned as FWK_SUCCESS from the
event handler.
Change-Id: Ibb56750f79d3b4f2f6ca82e655667f140563eede
=> DVFS: Event processing returns incorrect status

tools/build_system/rules.mk
New adjustments to the maximum size of the SCP_BL2 image in Trusted
Firmware-A means we now have far greater room for expansion.
Change-Id: I9bc4791e5a2347f2d30bdcb3a482b5a3e6801e0a
=> juno: Remove -Os/-flto for debug mode

module/scmi/include/internal/mod_scmi.h, module/scmi/src/mod_scmi.c, product/juno/scp_ramfw/config_scmi.c, product/rdn1e1/scp_ramfw/config_scmi.c, product/sgi575/scp_ramfw/config_scmi.c, product/sgm775/scp_ramfw/config_scmi.c, product/sgm776/scp_ramfw/config_scmi.c
This commit expands the detail of the log output of the SCMI module in
order to aid in debugging. Details that were previously missing,
including the message token and the service name, are now included.
Change-Id: I00075b3e4474328f27dc7f6be5b0df21c18c0cfb
=> scmi: Add extended logs

tools/ci.py
This patch is adding the -j flag when invoking
make to speed-up the compilation for all the
platforms.
Change-Id: Iad430b18380de895c645bf59104d4b2737c74d48
=> ci: Add -j flag

product/rddanielxlr/include/fmw_log.h
Release mode builds enables log buffering functionality with a buffer
size of 4KiB. This will result in log messages not written to the
console immediately. To avoid this in release builds, disable buffering
by setting the buffer size to 0.
Change-Id: Ie2319ae0c313a136de2fdb98c67f6a87584f2309
=> product/rddanielxlr: disable internal log buffer

module/scmi_perf/src/mod_scmi_perf.c
When a fast channel is set up it's memory is cleared. The wrong size
is used for the memset operation.
Change-Id: I278ef86606cacd050e3ca36186d3a0022b9fc284
=> SCMIv2: fix memory initialization of fast channels

tools/check_api.py, tools/check_tabs.py
Release 2.3.1 of pycodestyle does not allow the use of 'l'
as a variable.
Change-Id: I938515fdc0b6fe3e348995f1b35f0c98b311950e
=> tools: Fix Python code style errors

debugger/include/cli.h, debugger/src/cli/cli_fifo.c
This patch fixes the compile error seen when DEBUGGER flag is set
Change-Id: Ie9395eabf7b849cb43c2245cea3698bf916b915d
Signed-off-by: Jagadeeesh Ujja <jagadeesh.ujja@arm.com>
=> dbg: Fix the compile error when DEBUGGER flag set

module/dmc620/src/mod_dmc620.c
The assumption that a DMC module config would always have a valid
DDR PHY isn't always correct, for instance, in FVP environment(s).
Bypass binding to and configuring a DDR module if such is the case.
Change-Id: I82c7cada74bc89848dae8361a1d39565e9361c9c
Signed-off-by: Anurag Koul <anurag.koul@arm.com>
=> scp/dmc620: Skip binding to DDR module if it's not present

module/scmi_system_power/include/internal/scmi_system_power.h, module/scmi_system_power/src/mod_scmi_system_power.c
This patch adds the SYSTEM_POWER_STATE_NOTIFY command requesting
notifications on power state changes to the system power protocol.
This patch also adds the notification sent when a power state
change is requested.
Change-Id: I403d11005146fa447e980077b1f315c6a0e3564f
=> SCMIv2: Add SYSTEM_POWER_STATE_NOTIFY to system_power protocol

product/juno/scp_ramfw/firmware.mk, tools/build_system/doc.md
This patch allows the Debug Unit to be removed from the firmware
at build time if it is not required.
Change-Id: I51511ecd5b41a8ba498d6c1eb5a0cb57125c0f0b
=> juno/build: Make Juno Debug Unit optional

requirements.txt
The CI script requires certain Python packages to be available in order
to succeed. Adding a `requirements.txt` allows users to install all the
necessary requirements with:
pip install -r requirements.txt
Change-Id: I231bae45baea6196d728b8b82a26b994412aad8b
=> ci: Add `requirements.txt` for Python

framework/include/fwk_time.h, framework/src/Makefile, framework/src/fwk_log.c, framework/src/fwk_time.c, framework/test/Makefile, module/gtimer/include/mod_gtimer.h, module/gtimer/src/mod_gtimer.c, product/juno/scp_ramfw/config_timer.c, product/juno/scp_romfw/config_timer.c, product/juno/scp_romfw_bypass/config_timer.c, product/n1sdp/scp_ramfw/config_timer.c, product/rddaniel/scp_ramfw/config_gtimer.c, product/rddanielxlr/scp_ramfw/config_gtimer.c, product/rdn1e1/scp_ramfw/config_timer.c, product/rdn1e1/scp_romfw/config_gtimer.c, product/sgi575/scp_ramfw/config_timer.c, product/sgi575/scp_romfw/config_gtimer.c, product/sgm775/scp_ramfw/config_timer.c, product/sgm775/scp_romfw/config_timer.c, product/sgm776/scp_ramfw/config_timer.c, product/sgm776/scp_romfw/config_timer.c, product/synquacer/scp_ramfw/config_timer.c, product/synquacer/scp_romfw/config_timer.c, product/tc0/scp_ramfw/config_gtimer.c, product/tc0/scp_romfw/config_gtimer.c
This PR adds support for timestamping within the framework, and augments the logging framework with timestamp printouts generated by the generic timer on supporting platforms.
=> Add timestamping support

doc/framework.md
Fix source code presentation in doc/framework.md according to
markdown syntax.
Signed-off-by: Heyi Guo <guoheyi@linux.alibaba.com>
=> doc/framework.md: fix source code presentation

product/juno/scp_ramfw/config_sensor.c
If USE_FULL_SET_SENSORS is set, then the platform may append
additional sensors, including sensors for PVTs.
This patch adds a missing declaration for the pvt table size.
Change-Id: Iaa257b474cc710e8ff3f017fcc485962f40f7780
=> juno/config_sensor: Fix missing pvt_sensor_elem_table_size

product/n1sdp/module/n1sdp_rom/src/mod_n1sdp_rom.c
This patch sets the VTOR register from SCP ROM code before
jumping to the RAMFW adhering to the architectural changes
in framework.
Change-Id: I87dd519795d5c8bccc097121d96993caeec0c39f
=> n1sdp: set vector table offset value in ROM code

module/cmn600/src/mod_cmn600.c
The CMN-600 module currently incorrectly calculates the HN-F cache group
count for HN-F counts less than the number of HN-F entries per HN-F
cache group.
Change-Id: If840a78b8b70b1eb8b2b77768f4e95c0d8c369b3
=> cmn600: Fix incorrect cache group count calculation

framework/src/fwk_thread.c
The fwk_thread_put_event_and_wait processing could try and
use a NULL event if both the event queue and the ISR event queues
are empty.
Change-Id: I461a32c3040293c9c8928e60d01dc17bdefff4aa
=> fwk: fwk_thread_put_event_and_wait could process NULL event

module/scmi_system_power/src/mod_scmi_system_power.c
This change fixes a build issue if build enables
BS_FIRMWARE_HAS_SCMI_NOTIFICATIONS build macro. The build
gives undefined errors for macros SCMI_AGENT_ID_MAX and
SCMI_PROTOCOL_ID_SYS_POWER, which are recently renamed to
SCMI_AGENT_ID_MAX and MOD_SCMI_PROTOCOL_ID_SYS_POWER
respectively.
Change-Id: I1ba7d71d50bdc4a0c4913308e665840ab8a4b644
=> module/scmi_system_power: Fix build issue if enabled SCMI notification

module/scmi_perf/src/mod_scmi_perf.c
The build is broken if BUILD_HAS_FAST_CHANNELS_IS_SET.
Change-Id: Id9ec6637788ad217c07abe38ca83b131b1845f7a
=> module/scmi_perf: Fix build issues for Fast Channels

module/scmi_reset_domain/include/mod_scmi_reset_domain.h, module/scmi_reset_domain/src/mod_scmi_reset_domain.c
Add a policy handler for the SCMI Reset Domain protocol reset_request
command.
Change-Id: I58100a170401cb6f5ae7b5002178cf4d04729680
=> SCMI: Reset Domain policy handler

.clang-format, doc/code_style.md, doc/template/device.h
This patch updates the code style documentation, adjusting it to fit
existing established but undocumented rules, as well as introducing new
ones for consistency.
It also introduces a clang-format configuration, which becomes the de
jure code style arbitrator. This configuration uses a style very close
to the existing style, with some minor tweaks in places where a single
existing style was unestablished.
Change-Id: I7a6ae117a721d7e258df01a302c5a0fb18bc3133
=> doc: Add clang-format configuration

requirements.txt
This commit adds Clang Format as a Python wheel requirement, which
allowing users to install it automatically with:
pip install -r requirements.txt
Change-Id: If0046c8727a90957f68a5240a70678b6ec740537
=> requirements.txt: Add Clang Format 9.0.0

.clang-format
The first revision of `.clang-format` missed some necessary include
grouping options for the recently-introduced architecture headers.
Change-Id: I92eeeb6ee94693d129502a1ddc873f77fb0b408d
=> clang-format: Add architecture header group

product/juno/src/juno_scmi_clock.c
A debug trace message has the wrong format breaking
the juno build when LOG_LEVEL=TRACE.
Change-Id: Ie901bdedb87667ec9e28359ccf43d4b9d9512275
=> juno: Wrong format for LOG_LEVEL=TRACE

module/scmi_perf/src/mod_scmi_perf.c
If the fast channel is not implemented for the platform the
describe_fast_channels() API should return NO_SUPPORTED.
Change-Id: I9a53037831428e47f73d8e102bec120088f6ba19
=> SCMI_PERF: Describe Fast Channels API should return NOT_SUPPORTED

framework/src/fwk_multi_thread.c, framework/test/test_fwk_multi_thread_create.c, product/juno/scp_ramfw/rtx_config.c, product/n1sdp/mcp_ramfw/rtx_config.c, product/n1sdp/scp_ramfw/rtx_config.c, product/rddaniel/scp_ramfw/rtx_config.c, product/rddanielxlr/scp_ramfw/rtx_config.c, product/rdn1e1/scp_ramfw/rtx_config.c, product/sgi575/scp_ramfw/rtx_config.c, product/sgm775/scp_ramfw/rtx_config.c, product/sgm776/scp_ramfw/rtx_config.c, product/synquacer/scp_ramfw/rtx_config.c, product/tc0/scp_ramfw/rtx_config.c
The multithreaded implementation of the framework currently depends
directly on Keil RTX because it directly allocates the thread control
block itself.
This change instead replaces RTX's memory allocator with the framework's
memory allocator in a way that RTX can now allocate its own threads
through the generic CMSIS-RTOS interface.
Change-Id: Ie1bf2760a8f21c38a9466ff945d553e0e293a363
=> fwk: Remove dependency on RTX threads

module/scmi_perf/include/mod_scmi_perf.h, module/scmi_perf/src/mod_scmi_perf.c, product/juno/scp_ramfw/config_scmi_perf.c
In this patch fast channels are separated in different blocks,
to allow platforms to define each fast channel command separately
Also, the fast channel memory layout has been redefined for Juno
platform
Change-Id: Ic4e51251a43a340557c3d39a3422eae6de50371d
=> SCMI: Split performance domain fast channel commands

module/scmi_power_domain/src/mod_scmi_power_domain.c
This patch fixes a bug in the device set state.
For devices, the set_state api should be used and not the
set_state_async.
Change-Id: Iff76d68b4a506146d4d24ca215b4b8dd47678743
=> scmi_power_domain: Fix device set state

module/scmi_perf/src/mod_scmi_perf.c
The SCMI module was wrongly responding with a
SCMI_NOT_SUPPORTED error instead of a SCMI_NOT_FOUND,
when an invalid message id was sent for the command:
DESCRIBE_FASTCHANNELS. So, the modules were not
conformant to the SCMI specs.
Change-Id: I34104224815ee74eb1303ef0793e5dff99bda14a
Signed-off-by: Luca Vizzarro <Luca.Vizzarro@arm.com>
=> mod_scmi_perf: Fix fast channels wrong response

module/scmi/include/internal/scmi.h, module/scmi/include/internal/scmi_base.h, module/scmi_apcore/include/internal/scmi_apcore.h, module/scmi_clock/include/internal/scmi_clock.h, module/scmi_perf/include/internal/scmi_perf.h, module/scmi_power_domain/include/internal/scmi_power_domain.h, module/scmi_reset_domain/include/internal/scmi_reset_domain.h, module/scmi_sensor/include/internal/scmi_sensor.h, module/scmi_system_power/include/internal/scmi_system_power.h, module/smt/include/internal/smt.h, product/n1sdp/module/n1sdp_smt/include/internal/smt.h
This patch removes the __attribute((packed)) from all data structs.
The attribute is not required as all structs have correct internal
alignment.
Change-Id: I038e7c4e661133a8ee4915eb8abb45086145b93e
=> build: Remove packed attribute from data structs

module/scmi/src/mod_scmi.c, product/juno/scp_ramfw/config_resource_perms.c, product/rdn1e1/scp_ramfw/config_resource_perms.c, product/sgi575/scp_ramfw/config_resource_perms.c, product/sgm775/scp_ramfw/config_resource_perms.c, product/sgm776/scp_ramfw/config_resource_perms.c, product/tc0/scp_ramfw/config_resource_perms.c
Originally the command BASE_DISCOVER_LIST_PROTOCOLS of the base
SCMI protocol would always return all the implemented SCMI
protocols. Through the use of the resource management module,
the output can now vary according to the agent's level of
access. In this commit the PSCI agent level of access has now
been changed to the system power managament protocol only.
Change-Id: I80a9f6bb1746b62b171232b977abdb1f10d8de63
Signed-off-by: Luca Vizzarro <Luca.Vizzarro@arm.com>
=> mod_scmi: Adapt available protocols

product/n1sdp/module/n1sdp_pcie/src/mod_n1sdp_pcie.c
Removed the condition which stops the initialization and enabling
of PCIe in Remote Chip.
Change-Id: Ie2dcb3118efb73ede0d95af80364522216f59f9d
Signed-off-by: Sayanta Pattanayak <sayanta.pattanayak@arm.com>
=> n1sdp: enable pcie for remote n1sdp chip

arch/arm/armv7-m/src/arch_exceptions.c, arch/arm/armv7-m/src/arch_handlers.c, debugger/src/cli/cli_platform_time.c, doc/Doxyfile, framework/include/fwk_attributes.h, framework/include/fwk_log.h, framework/include/fwk_macros.h, framework/include/fwk_mm.h, framework/include/fwk_multi_thread.h, framework/include/fwk_notification.h, framework/src/fwk_log.c, framework/src/fwk_multi_thread.c, framework/src/fwk_notification.c, framework/src/fwk_time.c, module/fip/include/internal/fip.h, module/scmi_clock/src/mod_scmi_clock.c, module/scmi_perf/src/mod_scmi_perf.c, module/scmi_power_domain/src/mod_scmi_power_domain.c, module/scmi_reset_domain/src/mod_scmi_reset_domain.c, module/scmi_system_power/src/mod_scmi_system_power.c, module/statistics/include/mod_stats.h, product/juno/include/juno_clock.h, product/n1sdp/module/n1sdp_dmc620/src/dimm_spd.h, product/n1sdp/module/n1sdp_pcie/src/pcie_enumeration.c, product/n1sdp/module/n1sdp_scp2pcc/include/internal/n1sdp_scp2pcc.h, product/n1sdp/module/scmi_ccix_config/include/internal/mod_scmi_ccix_config.h, product/synquacer/module/scmi_vendor_ext/include/internal/scmi_vendor_ext.h, product/synquacer/module/synquacer_system/src/load_secure_fw.c, tools/cppcheck_suppress_list.txt
This pull requests adds a number of macros that act as facades for certain compiler extensions.
=> Add compiler-specific macro facades

module/dvfs/include/mod_dvfs.h, module/dvfs/src/mod_dvfs.c, module/scmi_perf/include/mod_scmi_perf.h, module/scmi_perf/src/mod_scmi_perf.c, product/juno/scp_ramfw/config_dvfs.c, product/juno/scp_ramfw/firmware.mk, product/rdn1e1/scp_ramfw/config_dvfs.c, product/sgi575/scp_ramfw/config_dvfs.c, product/sgm775/scp_ramfw/config_dvfs.c, product/sgm776/scp_ramfw/config_dvfs.c, product/tc0/scp_ramfw/config_dvfs.c
This patch allows the SCMI_PERF HAL to use whichever combination of
the SCMI Notifications and Fast Channels mechanisms (or neither) when
the DVFS module notifies it that there have been updates to the domain
performance limits or level settings.
Change-Id: I7e1c262edf33d090d21508eb8f1be293a0ab8e99
=> SCMI: Performance notifications and fast channels need to be separated

module/resource_perms/src/mod_resource_perms.c
This change fixes broken build with enabled
BS_FIRMWARE_HAS_SCMI_RESET
Change-Id: I9dfcfbfe47b0d835d1f8a4aadfde49627c7a2fc0
=> module/resource_perms: Fix broken build

framework/src/fwk_module.c
The default value of EVENT_COUNT is set to 64. On platforms that
requires larger number of notification subscriptions (192 for example),
EVENT_COUNT of 64 will not be sufficient. When platform sets the
max notification count greater than 64, set the EVENT_COUNT to
max notification count to account for additional events due to increased
notifications.
Change-Id: I9370703b47268c08d3f8bfb32b21f07b8b5370f7
=> framework: set event count from notification count

module/scmi_reset_domain/include/internal/scmi_reset_domain.h
The latest patches and rebase has revealed dependency of
internal/scmi_reset_domain.h on stdint.h. This change
fixes this.
Change-Id: I0b241d0b4d1ad5f99ce00ff99ab1a9094e2ce97d
=> module/scmi_reset_domain: Fix broken build with reset enabled

module/scmi_sensor/src/mod_scmi_sensor.c
The READING_GET command currently accepts any value
in the bits 31:1 in its flags. According to the SCMI
v2 specs these bits are reserved and must be zero.
This commit ensures that the command returns
SCMI_INVALID_PARAMETERS when any of those bits are set.
Change-Id: I8d0c486d6aa0a2df8c13b8d3f7319606402dd729
Signed-off-by: Luca Vizzarro <Luca.Vizzarro@arm.com>
=> scmi_sensor: Fix get readings invalid flags response

tools/build_system/rules.mk
Without this patch, the BUILD_PATH cannot end with a /.
With this patch, the end of BUILD_PATH does not matter.
BUILD_PATH can be automatically generated by build systems,
so it is important that any format is supported.
Change-Id: Iba306f8ac29a528fa6a7dc0a37e3c3b7ef7d0309
=> rules.mk: correct BUILD_PATH to allow build irrespective of format

product/tc0/scp_ramfw/config_dvfs.c, product/tc0/scp_ramfw/config_resource_perms.c, product/tc0/scp_ramfw/config_scmi_perf.c, product/tc0/scp_romfw/config_cmn_booker.c
This include:
- Changing DVFS frequencies from MHz to KHz inline with recently updated DVFS module
- Not initializing NULL elements, which is not allowed after early module context initializations
- Not setting permissions for SCMI clock, DPU requires access to SCMI clock
=> product/tc0: Fix runtime errors for tc0

framework/src/fwk_multi_thread.c, framework/src/fwk_thread.c, module/power_domain/src/mod_power_domain.c, product/juno/src/juno_scmi_clock.c
The logging framework does not remove the FWK_LOG_x code completely
when LEVEL_x is not set. This can lead to embedded code or macro's
being executed unnecessarily impacting performance.
Change-Id: I741b383cb74b2cf27740640769ea8f0fcd08fa2e
=> fwk: Remove all FWK_LOG_TRACE code when LOG_LEVEL=TRACE not set

module/dvfs/src/mod_dvfs.c
get_opp_for_voltage() should use voltage instead of level where looking
for an OPP.
=> module: dvfs: fix get_opp_for_voltage

module/scmi/include/mod_scmi_std.h, module/scmi_voltage_domain/include/internal/scmi_voltage_domain.h, module/scmi_voltage_domain/include/mod_scmi_voltage_domain.h, module/scmi_voltage_domain/src/Makefile, module/scmi_voltage_domain/src/mod_scmi_voltage_domain.c, module/voltage_domain/include/mod_voltage_domain.h, module/voltage_domain/src/Makefile, module/voltage_domain/src/mod_voltage_domain.c
Introduces a basic Voltage Domain driver and a SCMI voltage domain
protocol driver. SCMI voltage domain protocol is introduced in SCMI
specification v3.
Module voltage_domain is a generic HAL for voltage domains, aka power
supply regulators drivers. Based on module configuration, the module
binds each element to the voltage domain backend driver thru a generic
driver interface:
- set & get config, using SCMI voltage domain configuration format.
- set & get voltage level, in microvolt (uV)
=> module: Voltage Domain driver and related SCMIv3 protocol driver

product/tc0/scp_ramfw/config_pl011.c
The SYSTOP power domain is already ON in RAM firmware, therefore
do not wait for notification.
Change-Id: I9b2dc28fa2736169ce9f2dcec2e5986e5a994da5
=> tc0/pl011: Do not subscribe to power domain notification for pl011

tools/cppcheck_suppress_list.txt
This patch disables CI cppcheck for the Rcar product.
Change-Id: Ic9cbd4b2512bd0eb7bf79a5b3794fc8341307ea7
=> Rcar: Disable CPP checking for Rcar platform.

change_log.md, readme.md
This patch adds the release notes for v2.7.0. The change log lists the
major new features in the release.
Change-Id: Ia6ed47dcecf7936fd83fed8eb3acdc1ac1f5f76b
=> scp_v2.7: Release notes for SCP firmware v2.7.0

product/juno/module/juno_xrp7724/src/mod_juno_xrp7724.c
A previous commit [1] removed the status error when the margin is out of
margin. In fact this error is required to be returned so the HAL and its logic
to handle the error can take place.
Restore the error.
[1] 7b3bf3a2fc55d4a8f1a11ea416d791652f89e5da
Change-Id: Ieeaaaf23eaea85d8bfc26f0d74281f6c6114aed3
=> juno/xrp7724: Restore error on out of margin

module/scmi_system_power/include/mod_scmi_system_power.h, module/scmi_system_power/src/mod_scmi_system_power.c, product/morello/scp_ramfw_fvp/config_scmi_system_power.c, product/n1sdp/scp_ramfw/config_scmi_system_power.c, product/rddaniel/scp_ramfw/config_scmi_system_power.c, product/rddanielxlr/scp_ramfw/config_scmi_system_power.c, product/rdn1e1/scp_ramfw/config_scmi_system_power.c, product/sgi575/scp_ramfw/config_scmi_system_power.c, product/sgm775/scp_ramfw/config_scmi_system_power.c, product/sgm776/scp_ramfw/config_scmi_system_power.c, product/synquacer/scp_ramfw/config_scmi_system_power.c, product/tc0/scp_ramfw/config_scmi_system_power.c
When SCMI notifications are supported a timer is required to handle
graceful request. If this feature is not used timer_id must be
set to FWK_ID_NONE.
This patch also adds check for FWK_ID_NONE to prevent a binding
with no configuration set.
Change-Id: I25f982c2e8d686ac80dd0ebc2d9e64eac1522f3c
=> scmi_system_power/boards: Add default timer_id and add extra check

module/mock_sensor/src/mod_mock_sensor.c
This change fixes an undefined variable error in the get_value function.
Change-Id: Ib289094dcd945057505565e1179f6f4cf561de11
=> mock_sensor: fix error 'status' variable undefined.

tools/ci.py
In tools/ci.py we build rcar platform with aarch64-none-elf-gcc, but
we display it as 'ARM'.
Correct this by replacing ARM with GCC-AArch64.
Change-Id: I7c4de86f6cd4a2a007263703edee7a7c71dfa8f6
=> tools: Display correct name for rcar's compiler

framework/include/fwk_id.h, framework/src/fwk_id.c, framework/test/test_fwk_id_equality.c
This patch creates a new type called fwk_optional_id_t which can
be left  into undefined. This allows any non-mandatory configuration
to be left unassigned reducing code-size and improving upgradability.
Change-Id: I28243b6a9394ce7c476f6574c45e6fc55a9fd6c6
=> framework: add optional identifier support

module/scmi_clock/include/mod_scmi_clock.h, module/scmi_clock/src/mod_scmi_clock.c, product/juno/src/juno_scmi_clock.c
The policy handlers should only apply state changes when the operation
for the message is successfully completed.
Change-Id: I490dbeba3ea023ab71c4135dac5cdb6775594e92
=> SCMI: CLOCK_CONFIG_SET does not rollback changes when failure occurs

module/scmi_perf/src/mod_scmi_perf.c
According to the SCMIv2 spec section 4.1.4, if a command does
not exist then SCMI_NOT_FOUND must be returned. This commit
fixes this behaviour for the SCMI Performance Protocol.
Change-Id: I523ced9acf034ea4828c9b70096780ddc02e0ae5
Signed-off-by: Luca Vizzarro <Luca.Vizzarro@arm.com>
=> mod_scmi_perf: Fix invalid command return value

tools/build_system/rules.mk
arm-none-eabi-gcc --print-prog-name gcc-ar just prints gcc-ar, whereas
ar prints <prefix>/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ar
Signed-off-by: Jagadeesh Ujja <jagadeesh.ujja@arm.com>
Change-Id: I511fc2d307e2a8cd5e223013f9dfcc391e3969e0
=> Fix default value for AR

module/scmi_clock/src/mod_scmi_clock.c
The SCP firmware returned an error when an agent tries to set any
resource to its current state. This takes care of the behavior
when Uboot turns ON a resource and the kernel tries to again
enable it at boot (both are same agents on same mailbox channel).
Change-Id: Ib1f094ef008d36d9979f5b69a72440ca77c1813a
=> scmi_clock: Fix return code when resource is in requested state

product/rdn1e1/scp_ramfw/config_scmi.c, product/sgi575/scp_ramfw/config_scmi.c, product/sgm775/scp_ramfw/config_scmi.c, product/sgm776/scp_ramfw/config_scmi.c, product/tc0/scp_ramfw/config_scmi.c
Add disabled protocols configurations for sgm775,sgm776,sgi575,rdn1e1
and tc0 platforms when resource permissions option is disabled.
=> Add disabled PSCI protocols when resource permission feature is disabled

module/cmn700/src/cmn700.c
Range compare mode flag of non-hash regions should be checked against
NONHASH_RANGE_COMP_EN bit, not HTG_RANGE_COMP_EN bit.
Signed-off-by: Heyi Guo <guoheyi@linux.alibaba.com>
=> module/cmn700: Fix non-hash rcomp enable flag check bug

framework/include/fwk_attributes.h
GCC 10 onwards supports read_only, write_only and read_write attributes to
__access__ and only GCC 11 (which is unreleased at this point in time) also
supports none.
To fix the build on GCC 10, only use none with GCC 11.
Change-Id: I65a258fb2fc93874fe0b6fe5e695a6df030ce3a1
Signed-off-by: Ross Burton <ross.burton@arm.com>
=> fwk: only use __access__(none) with GCC 11

module/scmi_clock/src/mod_scmi_clock.c
The SCP firmware returned an error when an agent tries to set any
resource to its current state. This takes care of the behavior
when Uboot turns OFF  a resource and the kernel tries to again
enable it at boot (both are same agents on same mailbox channel).
Change-Id: Icfbddfb75eeb6247e9bd2bbe66434d8dbf988f13
=> scmi_clock: Fix return code when resource is in stopped state

product/morello/module/morello_pll/src/mod_morello_pll.c
In mod_morello_pll.c, there is an assert call to check the incoming
rate which is uint64_t with UINT16_MAX*FWK_MHZ. However the resulting
value is not stored in correct data type which causes calculation to
fail. This commit fixes this calculation.
Note, this is visible only in the debug build since assert calls are
enabled only in debug builds.
Change-Id: I682882bf52c68e099d8d9959915fa26744ae845f
=> product/morello: Fix comparison within assert

framework/src/fwk_id.c, module/dvfs/src/mod_dvfs.c, module/scmi_perf/src/mod_scmi_perf.c
In this patch all MISRA C:2012 mandatory defects are fixed.
In particular rule 9.1. As this is the mandatory rule affected.
Change-Id: I969906065d0dd28196d578f971adab24123c1cfb
=> scp: Fix Mandatory MISRA C:2012 defects

tools/build_system/rules.mk
Placed fwk_module_list.o file in the correct directory:
<Absolute path to SCP-firmware>/build/product/<product_name>/fw/release/obj/
instead of the extended and dulplicated path
<Absolute path to SCP-firmware>/build/product/<product name>/fw/release/obj/<Absolute path to SCP-firmware>/build/product/<product_name/fw/
=> Makefile: fix fwk_module_list.o location

framework/src/fwk_log.c
The condition that ensures `fwk_log_stream` is only set if `fwk_io_open` succeeds
is wrong - it only set `fwk_log_stream` if `fwk_io_open` failed.
=> fwk/fwk_log.c: fix erroneous check preventing log drain from working

CMakeLists.txt, cmake/Toolchain/ArmClang-Baremetal.cmake, cmake/Toolchain/ArmClang-Base.cmake, cmake/Toolchain/GNU-Baremetal.cmake, cmake/Toolchain/GNU-Base.cmake, cmake/Toolchain/Generic-Baremetal.cmake
This change is part of a larger CMake patch set, which will be introduced in the coming weeks. 
This PR adds some misc feature to CMake build system
Notably 
- Sets default build to release
- Adds C standards and C11 plus extensions
- Multi-toolchain support
Note: this is just a partial commit from CMake patch set and only done so that we can verify forthcoming patches on CI.
=> Cmake multi tool v1

CMakeLists.txt, arch/CMakeLists.txt, contrib/cmsis/CMakeLists.txt, contrib/cmsis/include/RTE_Components.h, framework/CMakeLists.txt, framework/include/fwk_module_idx.h.in, framework/src/fwk_module_list.c.in, module/CMakeLists.txt
This PR adds core CMake build support for the SCP firmware. However, note that this PR doesn't enable the building of any of the firmware targets.  Subsequent patches will be added in the coming weeks which will first support the building of the modules of the SCP firmware and later the actual firmware targets which will then finally enable the building of the platform-specific firmware binaries.  Also intended is a document that would explain how to build SCP firmware using CMake.
=> Cmake core v1

module/ppu_v1/include/mod_ppu_v1.h, module/ppu_v1/src/mod_ppu_v1.c, module/ppu_v1/src/ppu_v1.h, product/n1sdp/include/n1sdp_scc_reg.h, product/n1sdp/scp_ramfw/config_ppu_v1.c
This PR contains:
- Assigning opmode from product ppu configs
- Enable L3 cache from BOOTGPR1 reg for N1SDP
=> Ppu v1 opmode include

module/apremap/src/mod_apremap.c
The function that checks whether the address is above 2 GiB incorrectly
checks if the address is between 1 GiB and 2 GiB. Fix this.
Change-Id: I2d2a7a785a8d098a507a650f1b0db2cc2842f56c
=> apremap: fix 2 GiB range check

module/cmn_booker/include/mod_cmn_booker.h, module/cmn_booker/src/cmn_booker.c, module/cmn_booker/src/cmn_booker.h, module/cmn_booker/src/mod_cmn_booker.c, product/tc0/scp_romfw/config_cmn_booker.c
The CFGM base address calculation depends on the number of ports
per XP (cross-point).
Change-Id: Iabb9e76b86ee80b345857deb86e9acd4cec5988c
=> module/cmn_booker: amend CFGM base address calculation

module/cmn700/src/mod_cmn700.c
CMN-700 has new device type CCG which act as CXL gateway in addition to
CXRH, CXHA, CXRA (CCIX Gateway blocks). Exclude CCG device from the
count of devices that contain RNSAM table.
Change-Id: Ie253dcd40a7215c84a956d5978a7af8ebcc1c297
=> cmn700: exclude CCG devices when calculating external rnsam count

module/clock/src/mod_clock.c, module/gtimer/src/mod_gtimer.c, module/pl011/src/mod_pl011.c, module/ppu_v0/src/mod_ppu_v0.c, module/ppu_v0/src/ppu_v0.c, module/ppu_v1/src/mod_ppu_v1.c, module/ppu_v1/src/ppu_v1.c, module/sensor/src/mod_sensor.c, module/sid/src/mod_sid.c, product/sgm775/include/fmw_cmsis.h, product/sgm775/module/sgm775_ddr_phy500/CMakeLists.txt, product/sgm775/module/sgm775_ddr_phy500/Module.cmake, product/sgm775/module/sgm775_dmc500/CMakeLists.txt, product/sgm775/module/sgm775_dmc500/Module.cmake, product/sgm775/module/sgm775_system/CMakeLists.txt, product/sgm775/module/sgm775_system/Module.cmake, product/sgm775/scp_ramfw/CMakeLists.txt, product/sgm775/scp_ramfw/Firmware.cmake, product/sgm775/scp_ramfw/Toolchain-ArmClang.cmake, product/sgm775/scp_ramfw/Toolchain-GNU.cmake, product/sgm775/scp_romfw/CMakeLists.txt, product/sgm775/scp_romfw/Firmware.cmake, product/sgm775/scp_romfw/Toolchain-ArmClang.cmake, product/sgm775/scp_romfw/Toolchain-GNU.cmake
This change adds CMake build support for product/sgm775
Please note that firmware targets do not use libRTX_CM3.a
or RTX_CM3.lib, instead in CMake build, the library
is built using sources.
Change-Id: If5568e88d27689430013b701e0203bc579127ce7
Signed-off-by: Joel Goddard <joel.goddard@arm.com>
=> cmake: product/sgm775

product/rdv1/include/fmw_cmsis.h, product/rdv1/mcp_romfw/CMakeLists.txt, product/rdv1/mcp_romfw/Firmware.cmake, product/rdv1/mcp_romfw/Toolchain-ArmClang.cmake, product/rdv1/mcp_romfw/Toolchain-GNU.cmake, product/rdv1/module/platform_system/CMakeLists.txt, product/rdv1/module/platform_system/Module.cmake, product/rdv1/scp_ramfw/CMakeLists.txt, product/rdv1/scp_ramfw/Firmware.cmake, product/rdv1/scp_ramfw/Toolchain-ArmClang.cmake, product/rdv1/scp_ramfw/Toolchain-GNU.cmake, product/rdv1/scp_romfw/CMakeLists.txt, product/rdv1/scp_romfw/Firmware.cmake, product/rdv1/scp_romfw/Toolchain-ArmClang.cmake, product/rdv1/scp_romfw/Toolchain-GNU.cmake
This change adds CMake build support for rdv1 platform.
Please note that firmware targets do not use libRTX_CM3.a
or RTX_CM3.lib, instead in CMake build, the library
is built using sources.
Change-Id: If5528341e9380a5c0e53b8d11ce905089ddf6bd4
=> cmake: product/rdv1

doc/cmake_readme.md, module/apremap/CMakeLists.txt, module/apremap/Module.cmake, module/cmn700/CMakeLists.txt, module/cmn700/Module.cmake, product/rdn2/include/fmw_cmsis.h, product/rdn2/mcp_romfw/CMakeLists.txt, product/rdn2/mcp_romfw/Firmware.cmake, product/rdn2/mcp_romfw/Toolchain-ArmClang.cmake, product/rdn2/mcp_romfw/Toolchain-GNU.cmake, product/rdn2/module/platform_system/CMakeLists.txt, product/rdn2/module/platform_system/Module.cmake, product/rdn2/scp_ramfw/CMakeLists.txt, product/rdn2/scp_ramfw/Firmware.cmake, product/rdn2/scp_ramfw/Toolchain-ArmClang.cmake, product/rdn2/scp_ramfw/Toolchain-GNU.cmake, product/rdn2/scp_romfw/CMakeLists.txt, product/rdn2/scp_romfw/Firmware.cmake, product/rdn2/scp_romfw/Toolchain-ArmClang.cmake, product/rdn2/scp_romfw/Toolchain-GNU.cmake, tools/ci_cmake.py
This PR is the last in the ongoing PR series for CMake.
It includes.
- Support for building rdn2 platform.
- And update tool ci_cmake.py to build all platforms.
=> Cmake rdn2 v1

product/synquacer/include/fmw_cmsis.h, product/synquacer/module/ccn512/CMakeLists.txt, product/synquacer/module/ccn512/Module.cmake, product/synquacer/module/f_i2c/CMakeLists.txt, product/synquacer/module/f_i2c/Module.cmake, product/synquacer/module/f_uart3/CMakeLists.txt, product/synquacer/module/f_uart3/Module.cmake, product/synquacer/module/hsspi/CMakeLists.txt, product/synquacer/module/hsspi/Module.cmake, product/synquacer/module/ppu_v0_synquacer/CMakeLists.txt, product/synquacer/module/ppu_v0_synquacer/Module.cmake, product/synquacer/module/scmi_vendor_ext/CMakeLists.txt, product/synquacer/module/scmi_vendor_ext/Module.cmake, product/synquacer/module/synquacer_memc/CMakeLists.txt, product/synquacer/module/synquacer_memc/Module.cmake, product/synquacer/module/synquacer_pik_clock/CMakeLists.txt, product/synquacer/module/synquacer_pik_clock/Module.cmake, product/synquacer/module/synquacer_rom/CMakeLists.txt, product/synquacer/module/synquacer_rom/Module.cmake, product/synquacer/module/synquacer_system/CMakeLists.txt, product/synquacer/module/synquacer_system/Module.cmake, product/synquacer/scp_ramfw/CMakeLists.txt, product/synquacer/scp_ramfw/Firmware.cmake, product/synquacer/scp_ramfw/Toolchain-ArmClang.cmake, product/synquacer/scp_ramfw/Toolchain-GNU.cmake, product/synquacer/scp_romfw/CMakeLists.txt, product/synquacer/scp_romfw/Firmware.cmake, product/synquacer/scp_romfw/Toolchain-ArmClang.cmake, product/synquacer/scp_romfw/Toolchain-GNU.cmake
This change adds CMake build support for product/synquacer
Please note that firmware targets do not use libRTX_CM3.a
or RTX_CM3.lib, instead in CMake build, the library
is built using sources.
Change-Id: I886dd947c8d84d4ffb4d0a0f4c84defd4224d48b
=> cmake: product/synquacer

debugger/src/cli/cli.c
This commit add escape buffer overflow check when cli receive
escape sequence(cursor position response). escape buffer size
is 8 bytes, the last byte used to store string end symbol '\0'.
So the longest string escape buffer can save is 7 bytes. But in
some console or tool, the cursor position response sequence is
more then 7 bytes, and escap buffer will overflow. This patch
fix it.
Signed-off-by: Zhilong Wubin <zhilong.wb@alibaba-inc.com>
=> cli: fix escape buffer overflow check

framework/include/fwk_id.h, framework/src/fwk_id.c, framework/test/test_fwk_id_build.c
It is required to convert from sub-element index to identifier.
This patch adds the required new function.
Change-Id: I55f2702668ef97f7a6964adb924c3cedaae1e1e1
=> fwk: Add new function to retrieve sub-element id

Gemfile.lock, docker/Dockerfile
This PR brings:
- update kramdown to 2.3.1 to include a security issue fix
- update docker URL
=> Kramdown & docker fixes

arch/arm/armv7-m/src/arch_nvic.c
The type of "irq" needs to be aligned with IRQn_Type.
This patch fixes that.
Change-Id: I8fb5a4d9d891e78f01d6088aaad27d9c69daa9ef
=> armv7-m/arch_nvic:: Fix typecasting

Gemfile.lock
Bumps rexml from 3.2.4 to 3.2.5 as suggested by github.
Change-Id: Ibf982a3b2d07011b1d1f0926b6e9dbf33fec0f64
=> gemfile.lock: set rexml to use version 3.2.5 or later

Gemfile.lock
PR #464 updates to Gemfile.lock is wrong for rexml
version change. It updates the value at wrong place.
This updated commit fixes it.
Change-Id: I2650db000e0c35467d14d9832f7495a815008864
=> gemfile.lock: set rexml from 3.2.4 to 3.2.5

product/n1sdp/module/n1sdp_system/src/mod_n1sdp_system.c
This patch enables non-secure AXI access to CoreSight components
in both the primary and secondary boards in C2C setup.
Signed-off-by: Himanshu Sharma <Himanshu.Sharma@arm.com>
Change-Id: I000485fd30f87579b2b0a9b7f3935fe7ead99a7b
=> product/n1sdp: Enable non-secure CoreSight access in C2C setup

module/smt/include/internal/smt.h
There is an intermittent error on TF-A side when reading the mailbox.
The error is due to the mailbox message length not matching the expectation:
ASSERT: drivers/arm/css/scmi/scmi_pwr_dmn_proto.c:48
This is due to a race between SCP writing the data and TF-A reading them.
Effectively, the compiler seems to perform some minor optimisations with the
local mod_smt_memory resulting in the expected writing sequence to be altered.
This is seen in smt_respond().
To remove such optimisations, force the length and status to be volatile.
With this patch the sequence of writing into smt is restored and the error
in TF-A disappears.
Change-Id: I0127b9aa3cd1b54643ffdb2ca5ddce9fc9569bea
=> smt: Make status and length volatile for mod_smt_memory

debugger/src/cli/cli.c
Reverted a change that was causing the cli debugger to hang after a
character was entered.
Fixes 21acbdd473d87c23622bb65cb0ae4e27222e0b86 (cli: fix escape buffer overflow check)
Signed-off-by: Katherine Vincent <katherine.vincent@arm.com>
Change-Id: Ie6f54cb84ef7c0110ba93c8a1cc56679ec35a590
=> cli: fix to revert escape buffer overflow check

doc/code_rules.md, module/bootloader/src/mod_bootloader.c, module/pl011/src/mod_pl011.c, module/scmi/src/mod_scmi.c, module/scmi_perf/src/mod_scmi_perf.c, module/scmi_power_domain/src/mod_scmi_power_domain.c, module/scmi_sensor/src/mod_scmi_sensor.c, module/scmi_system_power/include/internal/scmi_system_power.h, module/scmi_system_power/src/mod_scmi_system_power.c, module/statistics/src/mod_stats.c, product/juno/scp_romfw_bypass/config_sds.c
This PR contains additional fixes for MISRAC required rules 15.6 and 10.1.
Rule 15.6: The body of an iteration‑statement or a selection‑statement shall be a compound‑statement
Rule 10.1: Operands shall not be of an inappropriate essential type
=> MISRAC Fixes rules 15.6 and 10.1

maintainers.md
Maintainers for n1sdp, RD platforms and Morello are updated.
Change-Id: I2b5d17ad4ad5e13261fd138489b50c802ff2349e
=> maintainers: Update maintainers for n1sdp, Morello, rd

module/cmn700/src/cmn700.c, module/cmn700/src/cmn700.h
This pull request adds the following three features to CMN-700 module:
- add support to configure additional non-hash mem regions
- update root node offset calculation for bigger mesh
Additionally there's a minor fix when checking the base address and size alignment.
=> CMN-700 features update

framework/src/fwk_thread.c
Since fwk_process_signal() enable global interrupt before updating 
fwk_signal_ctx.pending_signals, there can race with the increment
operation in fwk_thread_put_signal().
Call fwk_interrupt_global_enable() after updating the fwk_signal_ctx,
so that it can be protected by fwk_thread_put_signal().
Reported-by: Kazuhiko Sakamoto <sakamoto.kazuhiko@socionext.com>
Signed-off-by: Masami Hiramatsu <masami.hiramatsu@linaro.org>
=> Fix to protect fwk_signal_ctx from interrupts

framework/include/fwk_id.h, framework/src/fwk_id.c, framework/src/fwk_io.c, framework/src/fwk_log.c, framework/src/fwk_module.c, framework/src/fwk_time.c, module/clock/src/mod_clock.c, module/dvfs/src/mod_dvfs.c, module/dw_apb_i2c/src/mod_dw_apb_i2c.c, module/gtimer/src/mod_gtimer.c, module/i2c/src/mod_i2c.c, module/mhu/src/mod_mhu.c, module/mock_clock/src/mod_mock_clock.c, module/mock_psu/src/mod_mock_psu.c, module/pl011/src/mod_pl011.c, module/power_domain/src/mod_power_domain.c, module/psu/src/mod_psu.c, module/scmi/src/mod_scmi.c, module/scmi_apcore/src/mod_scmi_apcore.c, module/scmi_clock/src/mod_scmi_clock.c, module/scmi_perf/src/mod_scmi_perf.c, module/scmi_power_domain/src/mod_scmi_power_domain.c, module/scmi_sensor/src/mod_scmi_sensor.c, module/scmi_system_power/src/mod_scmi_system_power.c, module/sds/src/mod_sds.c, module/sensor/src/mod_sensor.c, module/smt/src/mod_smt.c, module/statistics/src/mod_stats.c, module/system_power/src/mod_system_power.c, module/timer/src/mod_timer.c
MISRA 10.3 defects relating to framework and module files will be addressed in this PR. 
The 10.3 rule states "the value of an expression shall not be assigned to an object with a narrower essential type or of a different essential type category".
=> MISRA 10.3 Defects within Module and Framework

module/bootloader/src/mod_bootloader.c
At reboot, the AP SRAM can retain its contents. In that case, if the
image flag indicating SCP RAM FW transfer isn't cleared, the ROM FW
will find a valid sds struct, with the flag set and copy whatever
is present in AP SRAM as SCP RAM FW for execution, before AP has
a chance to set the flag.
Hence clear the image flag, so that at reboot, the flag is set by AP only
after the RAM FW has been copied.
Change-Id: I88a574daa4876102a7390e227e23016c01cbf986
=> sds: clear data valid flag after SCP RAM FW has been transferred

framework/include/fwk_log.h, framework/src/fwk_log.c, module/cmn600/src/mod_cmn600.c, module/cmn650/src/mod_cmn650.c, module/cmn700/src/mod_cmn700.c, module/cmn_booker/src/mod_cmn_booker.c, module/power_domain/src/mod_power_domain.c, product/juno/include/fmw_log.h, product/morello/module/cmn_skeena/src/mod_cmn_skeena.c, product/morello/module/morello_rom/src/mod_morello_rom.c, product/morello/module/morello_system/src/mod_morello_system.c, product/n1sdp/module/n1sdp_c2c/src/mod_n1sdp_c2c_i2c.c, product/n1sdp/module/n1sdp_dmc620/src/dimm_spd.c, product/n1sdp/module/n1sdp_pcie/src/mod_n1sdp_pcie.c, product/n1sdp/module/n1sdp_rom/src/mod_n1sdp_rom.c, product/rdv1mc/module/platform_system/src/mod_platform_system.c, product/synquacer/module/synquacer_memc/src/synquacer_ddr.c, product/synquacer/module/synquacer_system/src/synquacer_main.c, product/synquacer/module/synquacer_system/src/synquacer_pd_manage.c
Currently the FWX_LOG_<LEVEL> macros provide a way to print or not messages in accordance with the LOG_LEVEL chosen at build time. The strings however are voided but not removed. This PR brings some improvements in order to remove unused strings in the FWK_LOG. Some preparatory patches are required in order to accommodate for such change in the logging framework.
=> Fwk log level improvements

module/scmi_clock/src/mod_scmi_clock.c
There are 2 calls to set_agent_clock_state() that are
missing the returned status check. This patch adds them.
Signed-off-by: Tuvshinzaya Erdenekhuu <tuvshinzaya.erdenekhuu@arm.com>
Change-Id: I517f7bb7a2a2138701a643548ec6293da59f3eb1
=> scmi_clock: Add missing check for returned status value

module/dvfs/CMakeLists.txt, module/scmi_perf/CMakeLists.txt
The scmi_perf module was left behind in a recent change for
the dvfs module.
This patch fixes the build with cmake.
Change-Id: I3c4b19f4a1b59a172b30f1cf1d1fb71f96f5e75d
=> dvfs/perf: Fix cmake target_link_libraries

Makefile.cmake, doc/cmake_readme.md, framework/test/CMakeLists.txt
This change adds CMake build and execute support for framework tests.
Also updated is the doc/cmake_readme.md with instructions for building
and executing framework tests.
Change-Id: I460398e26c427cd6af8da298c054377175c91d1c
=> CMake: Add support for framework tests

product/n1sdp/module/n1sdp_pll/include/internal/n1sdp_pll.h, product/n1sdp/module/n1sdp_pll/include/mod_n1sdp_pll.h, product/n1sdp/module/n1sdp_pll/src/mod_n1sdp_pll.c, product/n1sdp/scp_ramfw/config_clock.h, product/n1sdp/scp_ramfw/config_n1sdp_pll.c
To find optimal pll parameter values such as fbdiv, refdiv
and postdiv to achieve the closest freq to the actual rate.
Signed-off-by: Arnold Gabriel Benedict <arnoldgabriel.benedict@arm.com>
Change-Id: I02738ca43b9ceef833306d19130245f240a482b8
=> n1sdp: add dynamic calculations of PLL parameters

.devcontainer.json
VS Code currently tries to enter the container as the `user` user, which doesn't exist. Enter it as root instead.
=> vs-code: Fix VS Code development container

product/synquacer/module/ppu_v0_synquacer/src/mod_ppu_v0.c
On SynQuacer platform, whole system shutdown process is handled
by the SYNQUACER_SYSTEM module with accessing the CRG hardware.
This commit modifies the ppu_v0_synquacer shutdown handler
just to return FWK_SUCCESS, because no operation is required
in each PPU shutdown handler.
Change-Id: Ib76c07e940636ce7cf8e637533f898268f6b9464
=> synquacer: no operation is required in ppu_v0 shutdown handler

module/system_pll/src/mod_system_pll.c
The fucntion "freq_to_half_cycle_ps" should return unsigned int values
only. But the condition that checks whether the given frequency is a
multiple of 1 KHz, will return FWK_E_PARAM which is -1. So return 0
instead of FWK_E_PARAM, if the condition fails.
Change-Id: Ib31b65757ec3824ed945a4ac5a8e4abdf860e4a7
Signed-off-by: Shriram K <shriram.k@arm.com>
=> mod_system_pll: fix incorrect return value

product/morello/module/dmc_bing/CMakeLists.txt, product/morello/module/dmc_bing/include/mod_dmc_bing.h, product/morello/module/dmc_bing/src/mod_dmc_bing.c, product/morello/module/morello_system/CMakeLists.txt, product/morello/module/morello_system/src/mod_morello_system.c, product/morello/scp_ramfw_fvp/config_dmc_bing.c
dmc_bing module has been restructured so that both
Morello FVP and Morello SoC can make use of the same
module.
Signed-off-by: Chandni Cherukuri <chandni.cherukuri@arm.com>
Change-Id: Ib8e58b90560e2f5254d2393c7362b47f904e78e7
=> morello: Restructure dmc_bing module

cmake/Toolchain/GNU-Baremetal.cmake, contrib/cmsis/CMakeLists.txt
Currently -Wall, -Wextra and -Werror options are missing
for cmake builds. This commit add these options for
cmake builds.
Change-Id: I6d2f74f2cd03107127b87f80aa22764694190dac
=> cmake: Add -Wall -Werror options to cmake builds

framework/include/internal/fwk_id.h, framework/src/fwk_id.c
This change removes unused types
__FWK_ID_TYPE_SIGNAL and 'struct signal'
which are not needed as it's use was removed in the
below commit(part of light event patchset)
f74c34fc8 framework, dvfs: Remove signals.
Change-Id: I46b0c90ffc55893df5c2cebf461637ba91a8f3ce
=> framework: Remove signal type __FWK_ID_TYPE_SIGNAL

framework/src/fwk_id.c
A previous commit (7b01ad845) left behind one replacement from
assert() to fwk_assert().
This commit fixes that.
Change-Id: Id98d2d09bb25d2842beeff69b7938fe259d5938c
=> fwk: Replace remaining `assert()` call with `fwk_assert()`

module/cmn_booker/src/mod_cmn_booker.c, product/tc0/scp_romfw/config_cmn_booker.c, product/tc1/scp_romfw/config_cmn_booker.c
This is the max that CMN Booker can support. The corresponding
changes have been made in TC0 and TC1.
Change-Id: Ic8e52fdedbfa301c0b0b3fb1b7900e8caa375c14
=> cmn_booker: Limit PA width to 40 bits

doc/cmake_readme.md, framework/CMakeLists.txt, module/scmi/include/internal/scmi.h, module/scmi/include/mod_scmi.h, module/scmi/src/mod_scmi.c, module/scmi_perf/CMakeLists.txt, module/scmi_perf/src/mod_scmi_perf.c, module/scmi_perf/src/perf_plugins_handler.c
This PR brings assorted minor improvements:
- shorten logging strings
- simplification scmi_perf_notify_limits_update()
- remove redundant casting
- Cmake build fixes for Performance Plugin Handler
- enforce (cmake) build requirements for Performance Plugin Handler
and replace/remove non-inclusive terminology in scmi module.
=> SCMI minor improvements & inclusive terminology

module/scmi_perf/src/mod_scmi_perf.c
A MISRA 10.3 defect within scmi-perf will be addressed in this patch.
=> scmi_perf: Fix required MISRA defects rule 10.3

docker/Dockerfile
This patch sets a specific version (1.90) for cppcheck in order to
avoid unpredictable behaviours when a new version is publish and
allow it to properly test the new version before introducing it.
Change-Id: Ib12cbfbfaa233f58e7dd4beef3f98b3a18994cbf
=> Dockerfile: set specific version for cppcheck tool

product/synquacer/module/synquacer_system/src/mod_synquacer_system.c, product/synquacer/module/synquacer_system/src/synquacer_main.c
This commit implements the system power-off handling
by turning off the ATX power supply through GPIO.
Before this commit, system power-off handling is implemented
in Trusted Firmware-A running on the application
processor(cortex-a53). Since SCP is responsible for managing
system power, system power-off should be implemented in SCP-firmware.
Together with this SCP-firmware update, Trusted Firmware-A
PSCI system_off handling also needs to be updated to call
SCMI SYSTEM_POWER_STATE_SET command.
Change-Id: Ia96bc13ea5e74f892295dee3a4896bf5a7e6fb46
=> product/synquacer: implement system power-off

module/sensor/src/mod_sensor.c
Previous commit `989816611` removed the scmi_sensor header inclusion,
but that breaks the build when SENSOR_EVENTS are selected.
Reintroduce the header but this time guarded by its build definition.
Change-Id: I1200d78bafa84329a35e61f222cfde45f490053d
=> sensor: Reintroduce guarded scmi_senosr header inclusion

module/power_domain/include/mod_power_domain.h, module/power_domain/src/mod_power_domain.c, module/scmi_power_domain/src/mod_scmi_power_domain.c, module/scmi_system_power/src/mod_scmi_system_power.c, module/system_power/src/mod_system_power.c, product/juno/module/juno_debug/src/mod_juno_debug.c, product/juno/module/juno_ppu/src/mod_juno_ppu.c, product/morello/module/morello_system/src/mod_morello_system.c, product/n1sdp/module/n1sdp_c2c/src/mod_n1sdp_c2c_i2c.c, product/n1sdp/module/n1sdp_system/src/mod_n1sdp_system.c, product/rcar/module/rcar_pd_pmic_bd9571/src/mod_rcar_pd_pmic_bd9571.c, product/rcar/module/rcar_system_power/src/mod_rcar_system_power.c, product/rdn1e1/module/rdn1e1_system/src/mod_rdn1e1_system.c, product/rdn2/module/platform_system/src/mod_platform_system.c, product/rdv1/module/platform_system/src/mod_platform_system.c, product/rdv1mc/module/platform_system/src/mod_platform_system.c, product/sgi575/module/sgi575_system/src/mod_sgi575_system.c, product/synquacer/module/synquacer_system/src/synquacer_main.c, product/tc0/module/tc0_system/src/mod_tc0_system.c, product/tc1/module/tc1_system/src/mod_tc1_system.c
Now the SCMI Power domain is using the event-response mechanism to handle the synchronous requests.
=> Remove deprecated function fwk_thread_put_event_and_wait() from Power domain module  

product/morello/mcp_ramfw_soc/Toolchain-Clang.cmake, product/morello/scp_ramfw_soc/Toolchain-Clang.cmake
This patch adds LLVM support for soc build images.
Change-Id: I06c3e996e8a6bafaa74f2ea7985af3de48bdae2f
=> llvm/morello: Add support for soc build images

product/morello/scp_ramfw_fvp/config_armv7m_mpu.c, product/morello/scp_ramfw_fvp/config_smt.c
As per https://github.com/ARM-software/SCP-firmware/commit/9488bc401bb4e9289264368b7bb3ba702da276be#
the AP-SCP MHU mailbox memory region was moved from
SRAM to AP Non-trusted RAM for “scp_ramfw_soc” due
to the issue with unaligned accesses with MHU SRAM.
This patch is to align the same mailbox memory region
change for “scp_ramfw_fvp”.
Signed-off-by: Himanshu Sharma <Himanshu.Sharma@arm.com>
Change-Id: I8b63afc919ad83f77a47a629961659d4586aca01
=> morello: move MHU mailbox to AP non-trusted RAM for FVP

module/power_domain/include/mod_power_domain.h, module/power_domain/src/mod_power_domain.c, product/juno/module/juno_debug/src/mod_juno_debug.c
This patch reduces the overhead of queuing events for retrieving
the power state of a domain. It also removes a call to the
deprecated function fwk_thread_put_event_and_wait().
Change-Id: Id336ce6ccf1023f37970ae562faa5a4ccedb4642
=> pd/juno: Simplify get state request

framework/src/fwk_module.c
The fwk_module_get_data() and fwk_get_element_name() are not expected
to be called with invalid id. In this scenario, one of the framework
assert functions is used to terminate the program.
This warning was flagged by the static analysis tool.
Change-Id: I6341dede53ab3f8c1ceeaa0a8e5257a08eb1cc13
=> fwk_module: Mark code path as unexpected

module/system_power/src/mod_system_power.c
The product does not support or intend to use soc_wakeup_irq specifies
FWK_INTERRUPT_NONE to mod_system_power_config.soc_wakeup_irq field.
This commit checks that soc_wakeup_irq is valid before calling
fwk_interrupt_disable(). Without this change, system shutdown
fails because disable_all_irqs() returns FWK_E_DEVICE.
Change-Id: I8b318649eec5da98093880360c3dd27f02205902
=> system_power: accept the product does not support soc_wakeup_irq

product/synquacer/module/hsspi/src/hsspi_driver.c
This commit correctly waits the WIP bit after issuing
software reset command to the nor flash device, instead
of issuing software reset command repeatedly.
Change-Id: Ibc98a702ca9abe56a562e6aa4d498cf23bea050a
=> synquacer: fix spi nor flash software reset handling

module/ppu_v1/src/mod_ppu_v1.c
This patch removes reference to an uninitialized pointer to satisfy the
static analysis.There is no change in the functionality.
Change-Id: I17975e85afcdfc7592a5e567e32dd901023355ff
=> ppu: minor change to eliminate static analysis warning

doc/code_rules.md, tools/check_copyright.py
Minor fixes for:
- indentation on code rules
- max line length in check_copyright script
=> Code-rules/Check-copyright: Minor fixes - Jan 22

tools/ci_cmake.py, tools/product.py
This patch limits parallize build features in order to
reduce memory footprint and CPU resources needed to run
this test. It also reduces the number of simultaneous
builds performed. It only builds one product at a time.
Piped stdout stream is removed and stderr stream is
directly printed instead of being piped, this reduces
the memory footprint.
Change-Id: I2b0d8b0dc0021b3f554a45f700307b719f212bb0
=> fix/ci: limit parallize build

product/tc0/scp_ramfw/config_mpmm.c
The second highest OPP for Matterhorn ELP has 2612 kHz as
level.
The configuration in MPMM for that cluster report 2621 instead
of 2612.
This patch fixes to the correct level of 2612 kHz.
Change-Id: I129e1727f3cfd6c61c324d9d2285a8b63648db19
=> tc0/mpmm: Fix frequency value for m_elp_pct

module/cmn700/src/cmn700.c
If either the X or Y mesh size values of a CMN-700 mesh is greater than
eight, then the Node ID should be represented using a 11-bit format
with X and Y sizes encoded using 4-bits. So fix the check that
determines X and Y bit encoding size.
Signed-off-by: Tony K Nadackal <tony.nadackal@arm.com>
Change-Id: I76f8fb51953005c6b28aacd91e3ad40c728710b7
=> cmn700: fix encoding_bits for mesh size x or y > 8

framework/src/fwk_string.c, module/CMakeLists.txt, module/scmi_perf/doc/perf_plugins_handler.md, module/scmi_perf/include/mod_scmi_perf.h, module/scmi_perf/src/mod_scmi_perf.c, module/scmi_perf/src/perf_plugins_handler.c, module/scmi_perf/src/perf_plugins_handler.h, module/thermal_mgmt/CMakeLists.txt, module/thermal_mgmt/Module.cmake, module/thermal_mgmt/doc/thermal_mgmt.md, module/thermal_mgmt/include/mod_thermal_mgmt.h, module/thermal_mgmt/src/Makefile, module/thermal_mgmt/src/mod_thermal_mgmt.c, product/tc0/doc/variants.md, product/tc0/module/tc0_power_model/CMakeLists.txt, product/tc0/module/tc0_power_model/Module.cmake, product/tc0/module/tc0_power_model/include/mod_tc0_power_model.h, product/tc0/module/tc0_power_model/src/Makefile, product/tc0/module/tc0_power_model/src/mod_tc0_power_model.c, product/tc0/scp_ramfw/CMakeLists.txt, product/tc0/scp_ramfw/Firmware.cmake, product/tc0/scp_ramfw/config_mpmm.c, product/tc0/scp_ramfw/config_reg_sensor.c, product/tc0/scp_ramfw/config_scmi_perf.c, product/tc0/scp_ramfw/config_sensor.c, product/tc0/scp_ramfw/config_tc0_power_model.c, product/tc0/scp_ramfw/config_thermal_mgmt.c, product/tc0/scp_romfw/CMakeLists.txt, product/tc0/scp_romfw/Firmware.cmake
This PR brings a number of improvements and additions that are related together.
In particular:
- some fixes/improvements for fwk_string
- scmi_perf module: Fix for the plugins-handler dependency identifier
- performance plugins handler: additions to handle more than one plugin and support for full domains snapshot
- thermal management: add thermal management module to distribute power/performance across DVFS domains according to the thermal status of the platform
- TC0 software variant: TC0 is chosen as a reference platform to test three power/performance features available in firmware: MPMM, Traffic-cop and Thermal management.
=> Performance Plugins Handler & Thermal Management

product/morello/module/morello_system/src/mod_morello_system.c
Due to a corruption issue in the display output on the SoC, the slew
rate of the pixel clock output pad need to be changed from the default
FAST to SLOW.
Signed-off-by: Patrik Berglund <patrik.berglund@arm.com>
Change-Id: Id177a0151231395e89e8c3b357208730779a6af7
=> morello: change display pixel clock pad slew rate

product/rdn2/scp_ramfw/config_cmn700.c
To allow access of the CMN700 register space from Request Nodes, add
CMN700 address space as a RNSAM non-hashed region to route the accesses
for CMN700 configuration registers to the correct destination node i.e
HN-D node instead of DRAM.
Signed-off-by: Aditya Angadi <aditya.angadi@arm.com>
Change-Id: I62986ce0dab12bd6f45c9ef1993bbb15c03b94c7
=> product/rdn2: add mapping for cmn700 address space

module/thermal_mgmt/src/mod_thermal_mgmt.c
Recently fwk_thread_put_event function is been renamed to
fwk_put_event. However one instance of this is not updated
in mod_thermal_mgmt.c. This commit fixes this.
Change-Id: I81ce475b3e0b54abcaf8e7b1177733cb0e22b16f
=> thermal_mgmt: Fix undefined error for fwk_thread_put_event

product/morello/scp_ramfw_soc/CMakeLists.txt
Enable/disable the CLI debugger with the product common
CMake variable SCP_ENABLE_DEBUGGER.
Signed-off-by: Patrik Berglund <patrik.berglund@arm.com>
Change-Id: I0a68b213ba04af13c485e62b63fa5716083ce8b5
=> morello: Enable CLI debugger

module/scmi_sensor/include/internal/scmi_sensor.h, module/scmi_sensor/src/mod_scmi_sensor.c, module/sensor/include/mod_sensor.h, module/sensor/src/mod_sensor.c
The modifications included in these patches are for changing the sign for the value returned from get value from unsigned to signed and to simplify the trip point with a single 64 bit value.
=> Sensor SCMI V3 Changes

product/morello/scp_ramfw_fvp/config_armv7m_mpu.c, product/morello/scp_ramfw_soc/config_armv7m_mpu.c
The mailbox memory is shared between the SCP and the
OSPM agent, and is used for SCMI communication between
the two. The underlying memory region, which the
mailbox memory is mapped to, is currently configured as
Normal Memory (weak ordering) via the SCP MPU attributes.
This has been traced down to be the origin of the occasional
mailbox channel ownership errors as seen in the SCP FW logs -
the root cause being that on some occasions, the firmware
ends up reading the stale value of the channel ownership status
bit (as opposed to the reading value updated by the SCMI agent
during the SCMI comms) because of the reordering/buffering at
the interconnect.
Configuring the memory region to Strongly Ordered enforces a
strict ordering and gets rid of the mailbox channel ownership
errors. …
=> morello: Enforce strict ordering for mailbox memory

product/morello/module/dmc_bing/src/mod_dmc_bing.c
ADDRESS_CONTROL_NEXT and DECODE_CONTROL_NEXT register
values are modified for SoC which provides performance
improvement.
Signed-off-by: Chandni Cherukuri <chandni.cherukuri@arm.com>
Change-Id: I241a213152e74038e852bfc99a484208fb9fd62a
=> morello: modify DMC Bing registers for improved performance

arch/arm/armv7-m/include/arch_helpers.h, arch/arm/armv8-a/include/arch_helpers.h, arch/none/host/include/arch_helpers.h, framework/include/fwk_arch.h, framework/src/fwk_arch.c, framework/src/fwk_core.c, framework/test/arch_helpers.h, tools/build_system/doc.md
Currently, the firmware is busy looping forever while
waiting for any interrupts. This behaviour consumes power
unnecessarily. To avoid the busy loop scenario the firmware
will enter suspend state using WFE (Wait For Event)
instruction. Any interrupt will wake up the CPU to handle
new events.
Change-Id: I83508dcce721a6d3fb93fa598d03a4bb01331f00
=> fwk: SCP suspend execution until an interrupt occurs

product/synquacer/module/synquacer_memc/include/ddr_init.h
This commit enables the workaround for the DDR DQS gate training
issue of the DDR PHY.
Without this workaround, there is a possibility that DQS gate
training ends up in incorrect state.
Change-Id: Icba7c151cd80875dcdf26f579c58ea3da9b86c99
=> product/synquacer: enable DDR DQS gate training workaround

module/scmi_apcore/src/mod_scmi_apcore.c
From: Ard Biesheuvel <ardb@google.com>
AArch64 instructions are 32 bits wide, so the distinction between
AArch64 and AArch32 when deciding the minimum alignment of the
entrypoint address is not appropriate.
Signed-off-by: Ard Biesheuvel <ardb@google.com>
Change-Id: I31197b92ef0307f9ef0f971c23c7cf146032a66e
=> scmi/apcore: permit 32-bit alignment for 64-bit regwidth entrypoints

module/gtimer/include/mod_gtimer.h, module/gtimer/src/mod_gtimer.c, product/rdn1e1/include/mcp_rdn1e1_mmap.h, product/rdn1e1/mcp_ramfw/config_gtimer.c, product/rdn2/include/mcp_css_mmap.h, product/rdn2/include/mcp_mmap.h, product/rdn2/mcp_ramfw/config_gtimer.c, product/rdv1/include/mcp_css_mmap.h, product/rdv1/include/mcp_mmap.h, product/rdv1/mcp_ramfw/config_gtimer.c, product/rdv1mc/include/mcp_css_mmap.h, product/rdv1mc/include/mcp_mmap.h, product/rdv1mc/mcp_ramfw/config_gtimer.c, product/sgi575/include/mcp_sgi575_mmap.h, product/sgi575/mcp_ramfw/config_gtimer.c
- This patch-set fixes the the gtimer config in mcp ramfw for Infra RD platforms. 
- It also introduces a new flag in the gtimer module to make the CNTCONTROL register initialization optional.
=> Fix gtimer config in Infra RD platforms mcp ramfw.

CMakeLists.txt, Makefile, framework/test/CMakeLists.txt, readme.md
This patch updates the SCP-firmware version to 2.10.0.
Change-Id: Ic2bfe27a17f407a18f98b69154eb97c774a0a288
=> scp: Update firmware version to 2.10.0

doc/cmake_readme.md, user_guide.md
As using Make is deprecated,update the documentation
accordingly so that only the CMake build system,
commands and dependencies are mentioned.
This commit also updates some minor changes/errors
in documentation.
Change-Id: I563d9ee343b4ab07c4e0d8d4845b8b574b31dde0
=> doc: cmake and minor documentation corrections

module/clock/src/clock_tree_management.c
The assertions were checking that the status _is_ FWK_E_SUPPORT
instead of checking that it is _not_ FWK_E_SUPPORT
=> clock: Fix wrong async driver assertions

module/clock/src/clock_tree_management.c
When calling the clock driver's get_state API, the provied id should be
the driver element id, and not the clock's element id.
Fixed a call to get_state that was using the clock id.
=> clock: Fix call to get_state to use driver id instead of clock id

module/scmi_perf/src/mod_scmi_perf.c
Minor fixes for the scmi_perf module: Fix a typo and fix a MISRAC pointer type conversion rule.
=> Scmi perf fixes: typo & pointer conversion rule

tools/ci_cmake.py, tools/product.py
The CI is indicating whether the build failed or passed,
but is not printing the output of the build, which is
making it difficult to debug any problems that arise when
running the cmake-ci tests.
Generate files with the information of each build's output.
Store those files in the path given by the parameter -bod
(build output directory) or under the default folder
/tmp/scp/build-output.
Change-Id: I1b45cee047a23e54e4fe2f24414001b583c706bc
=> ci: Print build output/information

module/scmi/include/internal/mod_scmi.h, module/scmi/include/mod_scmi.h, module/scmi/src/mod_scmi.c, module/smt/src/mod_smt.c
This patch series enables the SCP to initiate SCMI messages and also adds support for requester type SMT channel message handler.
=> SCP SCMI Initiator Patches

cmake/Toolchain/ArmClang-Baremetal.cmake
Images generated for cortex-m7 targets are not booting.
This is because hardware floating point initialization modules
are added by ArmClang linker. These modules add floating point
instructions that cause exceptions.
This patch adds the linker option to omit including the floating
point initialization modules and the compiler option to avoid
using floating point instructions.
Change-Id: I7e0f868227587c0a167d29974608ddb2a21b018f
=> cmake: Fix ArmClang generated images

product/morello/scp_ramfw_soc/config_timer.c
The generic timer instance is not hooked to the framework time driver
which makes the timestamp to be printed as zeros all the time.
This patch fixes the gap to let framework print correct timestamps
during debug logs.
Change-Id: Iacab58a01999be8f71358d13e48c1517dba02b64
=> morello: fix timestamp in debug logs

product/synquacer/doc/platform_options.md, product/synquacer/include/fmw_io.h, product/synquacer/include/system_clock.h, product/synquacer/scp_ramfw/CMakeLists.txt, product/synquacer/scp_ramfw/Firmware.cmake, product/synquacer/scp_ramfw/config_pl011.c, product/synquacer/scp_ramfw/firmware.mk
This patch adds a new make option to select UART port
in make and CMake build on SynQuacer platform.
The following 3 UART ports are selectable.
uart0 : A standard UART on the 40 pin expansion connector
(used as default for SCP console)
uart1 : A second standard UART on the 40 pin expansion connector
debug_uart : A debug UART via the micro-B USB connector
To select UART port, set SYNQUACER_UART value as below
when executing make commnad.
In make build system,
make CC=$CC PRODUCT=synquacer MODE=$MODE \
[SYNQUACER_UART=uart0|uart1|debug_uart]
e.g.
make CC=$CC PRODUCT=synquacer MODE=$MODE SYNQUACER_UART=uart1
In CMake build system,
make -f Makefile.cmake CC=$CC PRODUCT=synquacer MODE=$MODE \
[EXTRA_CONFIG_ARGS="-DSYNQUACER_UART=uart0|uart1|debug_uart"]
e.g.
make -f Makefile.cmake CC=$CC …
=> synquacer: Add a make option to select UART port

module/reset_domain/src/mod_reset_domain.c, product/juno/scp_ramfw/config_reset_domain.c
This PR brings two fixes for the reset domain:
- Fix HAL api type for mod_reset_domain
- Fix conditional inclusion of notification_id for juno/reset_domain
=> Reset domain fixes: HAL type and notification_id

framework/CMakeLists.txt, module/mock_sensor/include/mod_mock_sensor.h, module/mock_sensor/src/mod_mock_sensor.c, module/reg_sensor/src/mod_reg_sensor.c, module/sensor/include/mod_sensor.h, module/sensor/src/mod_sensor.c, product/juno/module/juno_adc/src/mod_juno_adc.c, product/juno/module/juno_pvt/src/mod_juno_pvt.c, product/juno/module/juno_xrp7724/src/mod_juno_xrp7724.c, product/morello/module/morello_sensor/src/mod_morello_sensor.c, product/n1sdp/module/n1sdp_sensor/src/mod_n1sdp_sensor.c, product/rcar/module/rcar_reg_sensor/src/mod_rcar_reg_sensor.c, tools/cppcheck_suppress_list.txt
The changes in this patch are to introduce a typedef, which will
allow either signed or unsigned sensor values. This new typedef is
used to be able to conditionally support int64, allowing the
introduction of negative value sensors.
It will be automatically enabled with SCMI-sensor-v2, however it
can also be enabled on its own using with the cmake tag
SCP_ENABLE_SENSOR_SIGNED_VALUE.
Existing platforms that cannot handle signed values will return
FWK_E_SUPPORT when the above build options are set.
Signed-off-by: Katherine Vincent <katherine.vincent@arm.com>
Change-Id: I0f24e31d4bc3861b1724d814e866ef97f09c4b88
=> sensor: typedef included to give signed or unsigned value options

arch/none/host/include/arch_helpers.h
Some compilers complain the return type error as below.
| arch/none/host/include/arch_helpers.h: In function ‘arch_interrupts_disable’:
| arch/none/host/include/arch_helpers.h:25:1: error: no return statement in
|	function returning non-void [-Werror=return-type]
Fix the same.
Change-Id: Ia3343fbbea57ae783b272f0c4db05a7060256f85
Signed-off-by: Sudeep Holla <sudeep.holla@arm.com>
=> fwk: Return a value from a non-void function

readme.md
Update readme.md so that the reference to SCMI points to v3.1 instead of v1.0.
Signed-off-by: Chuyue Luo <Chuyue.Luo@arm.com>
Change-Id: I85d04d53b1da3c45f58c15f1524c6e9e4ad07a03
=> readme: Update SCMI reference to v3.1

product/synquacer/include/efi.h, product/synquacer/include/fwu_mdata.h, product/synquacer/include/synquacer_mmap.h, product/synquacer/module/synquacer_system/src/load_secure_fw.c, product/synquacer/module/synquacer_system/src/synquacer_main.c
Add FWU Multi Bank Update and boot BL2 from FIP image support for
SynQuacer platform.
When the DSW 3-4 is on, SynQuacer platform will decode FWU metadata
and platform metadata to choose the active bank of the FIP image
and boot BL2 from it.
This also enables the platform trial boot, which count up the boot
counter in the platform metadata, and when it reaches to the limit
(== 3) it switch back to the previous active bank. This counter will
stop when the BL33 (typically U-Boot) clears the counter.
Signed-off-by: Jassi Brar <jaswinder.singh@linaro.org>
Signed-off-by: Masami Hiramatsu <masami.hiramatsu@linaro.org>
Change-Id: I00b9c932fac5b4a9a231fcf2a050b766abefed61
=> FWU: synquacer: Add FWU Multi Bank Update and BL2 boot support

product/rdn2/scp_ramfw/CMakeLists.txt, product/rdn2/scp_ramfw/Firmware.cmake, product/rdn2/scp_ramfw/config_scmi_perf.c, product/rdv1/scp_ramfw/CMakeLists.txt, product/rdv1/scp_ramfw/Firmware.cmake, product/rdv1/scp_ramfw/config_scmi_perf.c, product/rdv1mc/scp_ramfw/CMakeLists.txt, product/rdv1mc/scp_ramfw/Firmware.cmake, product/rdv1mc/scp_ramfw/config_scmi_perf.c
This patch series enable CPPC support with cmake build system. This series also fixup the performance domain count in the configuration data.
=> Enable CPPC on cmake build and update SCMI perf configuration.

tools/ci_cmake.py, tools/product.py
The CI is only testing the build for the default log
level.
Add a parameter "ll" (log-level) to test the builds
with a specified log level.
This is done so that multiple runs of the ci_cmake
tests can be done in parallel by calling this script
multiple times with the different log levels.
These changes are done while improving the readability
of the constructor calls of Build() with the different optional
parameters.
Change-Id: I30004a65194618237643464b19337bafdde26610
=> ci: add build for each log level

Makefile.cmake
It looks like lcov is incompatible with other tools such as
compiler. This is causing pull requests to fail.
This patch temprory disables code coverage to investigate it
further.
Change-Id: I2f3fb7fafee0c30ed05fbd34d8fa62a7470a23d2
=> Makefile.cmake: Disable code coverage

product/morello/scp_ramfw_fvp/config_dvfs.c
Aligning the CPU frequency values for DVFS in Morello FVP with
the values configured in Morello SoC
Signed-off-by: Himanshu Sharma <Himanshu.Sharma@arm.com>
Change-Id: I8df7efb59c8c41701bfe60db431d947ba6329f71
=> product/morello: align DVFS frequency values of FVP with SoC

arch/arm/arm-m/CMakeLists.txt, cmake/Toolchain/Clang-Base.cmake, product/rdfremont/lcp_ramfw/Toolchain-ArmClang.cmake, tools/ci_cmake.py
This PR includes:
1) Workaround Armclang issue with cmake versions older than 3.21
2) Updating used LLVM version to 13 to support cortex-m55
3) Adding rdfremont target (which includes a cortex-m55 target) to CI tests
=> Include support for Armv8m in CI tests

tools/ci_cmake.py
This patch adds missing variants in `ci_cmake.py` script
for RDN2.
Change-Id: I6f5fb512cc7f2fc62d3586f259ee3c536ac24094
=> ci_cmake: adds variant 1 and 2 for RDN2

product/rdn2/src/config_sid.c
Add support for RD-Edmunds platform variant. This variant and the RD-N2
platform share the same variant number, that is 0, but have different
part numbers. So add a new element in the SID module configuration to
support the RD-Edmunds part number as well.
Signed-off-by: Tony K Nadackal <tony.nadackal@arm.com>
Change-Id: I848367b1025308e094f71a2ad6f7f8ed853aeb17
=> product/rdn2: add support for RD-Edmunds platform variant

product/rdn2/scp_ramfw/config_pcie_integ_ctrl.c
On RD-N2-Cfg1 (variant 1), non-pcie devices are behind the IO Macro #1. The PCIe devices are only behind IO Macro#0.
So remove initialization of PCIe configurations for IO Macro #1.
=> Fix number of PCIe enabled IO-Macros for RD-N2-Cfg1

Makefile.cmake
This reverts commit 865d14fb580e2338e376128995b2c6ba059cde19.
This is because the node environment has been updated to
support this feature.
Signed-off-by: Brett Warren <brett.warren@arm.com>
Change-Id: Ide94c588070473efcc061b3bdf35ccf04eabf75b
=> Revert "Makefile.cmake: Disable code coverage"

CMakeLists.txt
Currently firmware target elf file is not clearly recognised
due to the missing extension(.elf). This change fixes this.
Change-Id: I2f2977761144e9aae2ed8b65e2447d15870bfb7d
=> CMake: Add elf extension to firmware target

module/cmn700/include/internal/cmn700_ctx.h, module/cmn700/src/mod_cmn700.c
Every internal RN-SAM node has 32 SYS_CACHE_GRP_SN_NODEID registers to
store corresponding SNF ids. Each SYS_CACHE_GRP_SN_NODEID register
targets four SN node IDs. Previously, the value for each register was
calculated iteratively and was stored in the sn_nodeid_group[group]
array temporarily. Once the entire calculation was over, the contents of
the array were assigned to the corresponding SYS_CACHE_GRP_SN_NODEID
registers.
The values in the sn_nodeid_group[group] array were not cleared before
the calculation of the next RN-SAM nodes. This caused incorrect
calculation of the SYS_CACHE_GRP_SN_NODEID register values for the next
RN-SAM nodes.
To fix this, this patch directly calculates SYS_CACHE_GRP_SN_NODEID
values for each cache group from the values in the snf_table array. The
array …
=> cmn700: fix SYS_CACHE_GRP_SN_NODEID calculation

product/morello/module/dmc_bing/src/mod_dmc_bing.c
Morello SoC supports 32 GB dual rank DIMMs. To support
this, the RTT_PARK value is updated to work with the dual
rank DIMMs.
Signed-off-by: Chandni Cherukuri <chandni.cherukuri@arm.com>
Change-Id: I85c442a618163a6b4e8de88c9e512f4733b773fd
=> morello: Updated the RTT_PARK setting for dual rank DIMM

module/timer/include/mod_timer.h
The timer module depends on the timer driver to enable and
disable the timer's interrupt source, however the timer module is
the one that clears the interrupt flag.
This behavior is explained in the timer driver API to avoid
ambiguity for timer driver developers.
Change-Id: I982a9bffd3618c6b514e280e4601d4a58a9ce34a
=> mod_timer: Add clarifying comments

product/rdn2/scp_ramfw/config_cmn700.c, product/rdn2/scp_ramfw/config_pcie_integ_ctrl.c
Update the base address of the SoC expansion block from 0xC000_0000_0000
to 0x10_8000_0000. This SoC expansion block is connected to one of the
IO Virtualization block present on RD-N2 platforms.
Update this base address in cmn-700 descriptor and the pcie integration
control config.
=> product/rdn2: update base address of expansion block

unit_test/module_common.cmake
MOCK_REPACEMENTS was accumulating strings from
previously run test modules. This variable is now
reset after module_common.cmake is invoked.
=> module_common: fix MOCK_REPLACEMENTS reset

module/cdns_i2c/include/internal/cdns_i2c.h, module/cdns_i2c/src/mod_cdns_i2c.c
Bump up the I2C interface timeout to the maximum value supported by the IP. This is particularly useful when communicating with slow I2C target devices.
Also, reset the I2C FIFO at the start of a Tx/Rx
sequence in order to clear any error state latched for a previously failed transaction.
Change-Id: I3c7aa91fcc5515c41c482cdc0249b6b0024ad616
Signed-off-by: Anurag Koul <anurag.koul@arm.com>
=> module/cdns_i2c: Enhance I2C error handling

product/rdn2/scp_ramfw/config_cmn700.c
Remote agentid in Chip-0's config data for Chip-1 is pointing to the local agentid's instead of the remote agentid. Fix this.
=> product/rdn2: fix remote_agentid for chip-0 to chip-1 data

CMakeLists.txt, Makefile, framework/test/CMakeLists.txt, readme.md
This patch updates the SCP-firmware version to 2.11.0.
Change-Id: I9f85b3113a2cd3bb057f58ac3b1750f5a326aaf3
=> scp: Update firmware version to 2.11.0

module/mhu3/src/mod_mhu3.c
To trigger an interrupt on a doorbell channel
corresponding PDBCW_ST bit of the PBX(postbox) is validated. If corresponding bit is unset then the code will raise the doorbell interrupt, otherwise it will return an error FWK_E_STATE. This validation check is incorrect and this change fixes this.
Change-Id: I84b19832b1d128176a2b77f2f5abc3c3cb1d92c0
=> mod/mhu3: Fix doorbell channel trigger interrupt

product/synquacer/module/synquacer_memc/include/synquacer_ddr.h, product/synquacer/module/synquacer_memc/src/ddr_init.c
When the TF-A BL2 is enabled on the SynQuacer platform, BL31 does not fit in the secure SRAM(512KiB).
This commit allocates the additional 1MiB secure DRAM for BL31.
Change-Id: Icba17f4a183f75a180d23a100f0b68d60f60f06a
=> synquacer: allocate secure DRAM for BL31

module/scmi_power_domain/src/mod_scmi_power_domain.c
Since commit 656f089b97d5 ("scmi_pd:Add power domain set state sync request handling"), the scmi_power_domain module incorrectly masks the power state parameter for device power domains.
The SCMI specification defines a parameter of value 0 as the ON state, and value 0x40000000 as the OFF state. Any other value for bits 27:0 is IMPLEMENTATION DEFINED. Currently, in order to convert the SCMI parameter into an internal state, scmi_pd_power_state_set_policy() masks all bits but 27:0, so that a OFF parameter incorrectly matches MOD_PD_STATE_ON. To fix it, compare the complete parameter value against pd_state_to_scmi_dev_state.
Signed-off-by: Jean-Philippe Brucker <jean-philippe@linaro.org>
=> scmi_pd: Fix handling of device power OFF

module/power_domain/include/mod_power_domain.h, module/power_domain/src/mod_power_domain.c, module/scmi_system_power/src/mod_scmi_system_power.c, product/rdn2/module/platform_system/include/mod_platform_system.h, product/rdn2/module/platform_system/src/mod_platform_system.c
Add warm reboot support for RD-N2 platform. During warm reboot, all the CPUs will be powered OFF by keeping rest of the logics in ON state. Once all the CPU completes power down, power ON the boot CPU to start the boot sequence.
=> Add warm reboot support for RD-N2 platform

product/rdn2/src/config_sid.c
Neoverse Reference Design platform RD-Edmunds has been renamed to RD-V2 and all corresponding references have been changed.
Signed-off-by: Joel Goddard <joel.goddard@arm.com>
Change-Id: Ib77cd064403cd162339b3507536dcb296e4b2557
=> product: rename RD-Edmunds to RD-V2

product/morello/scp_ramfw_fvp/config_css_clock.c, product/morello/scp_ramfw_fvp/config_dvfs.c, product/morello/scp_ramfw_soc/config_dvfs.c
Change the DVFS sustained index of the Morello platforms (SoC and FVP) to boot at the highest supported OPP level.
Signed-off-by: Anurag Koul <anurag.koul@arm.com>
Change-Id: Id2dfb5fa585d9aae03249496348529e5304c3e97
=> morello: Configure the default OPP to the highest

product/rdfremont/lcp_ramfw/CMakeLists.txt, product/rdfremont/lcp_ramfw/Firmware.cmake
All the firmware targets in the codebase terminate with -blX. This is useful to understand the load stage and required to be aligned with other platforms.
rdfremont/lcp target is missing the -blX, so let's add it.
Change-Id: I895dfd995847113aba32fea433afaabfafa03e2c
=> rdfremont/lcp: Append bl2 to firmware target

module/power_domain/src/mod_power_domain.c
Fixes power_domain.c that macro used FWK_LOG_LEVEL_ERR whereas error trace level macro is FWK_LOG_LEVEL_ERROR and to define local get_state_name() helper function when at least error trace level is enabled.
=> module: power_domain: fix trace resources

module/optee/mbx/src/mod_optee_mbx.c
Fixes optee_mbx_signal_smt_message() to assert context content after the context pointer is initialized.
=> modue: optee_mbx: use context after its initialized

module/mhu3/src/mod_mhu3.c, module/mhu3/test/CMakeLists.txt, module/mhu3/test/config_mhu3.h, module/mhu3/test/fwk_module_idx.h, module/mhu3/test/mocks/.clang-format, module/mhu3/test/mod_mhu3_unit_test.c, unit_test/CMakeLists.txt, unit_test/unity_mocks/mocks/Mockfwk_interrupt.c, unit_test/unity_mocks/mocks/Mockfwk_interrupt.h
This PR mainly adds unit tests for MHUv3 driver. see [module/mhu3: Add unit tests](https://github.com/ARM-software/SCP-firmware/commit/62ea9c26061ce6d3f638385ecadfebf8e3ad7dc1)
It also adds misc dependency changes such as [unit_test: Regenerate mocks for fwk_interrupt.h](https://github.com/ARM-software/SCP-firmware/commit/0aeafcd275d7b10fc4dea5a31e7e7c2c8a7810a4) and minor fix in MHUv3 driver
=> MHUv3 Unit tests and misc dependency changes 

product/optee-stm32mp1/include/fmw_io.h
Adds fwm_io.h to product optee-stm32mp1 to get optee_console device bound to framework log support.
=> product/optee-stm32mp1: configure log

module/CMakeLists.txt
Some platforms have special feature need to slightly modify upstream module. Add option to replace with the module defined in product path.
Change-Id: I1dc89ca49eecb1f2fb2e2537234cea7f98116c1c
Signed-off-by: Joe Zhu <Chunguang.Zhu@verisilicon.com>
=> module: cmake: add option to replace modules

tools/check_copyright.py, tools/check_spacing.py, tools/check_tabs.py
It should be possible to add multiple unit-test files for one module. Each file must be in a separate subdirectory under the module test directory. The tools checking for spacing, tabs, and copyright must consider this configuration.
Change-Id: If02db0f0c190736b193494109915eb6e0f8ec592
=> tools: Update unit-test related checks

arch/none/optee/src/arch_main.c, module/dvfs/src/mod_dvfs.c, module/mock_ppu/src/mod_mock_ppu.c, module/optee/mbx/src/mod_optee_mbx.c, module/scmi_power_domain/src/mod_scmi_power_domain.c
Few occurence of `#if BUILD_HAS_xxx` are replaced with `#ifdef BUILD_HAS_xxx`.
=> Fix inconsistencies with BUILD_HAS_xxx

cmake/SCPModuleTrace.cmake, doc/framework.md, framework/CMakeLists.txt, framework/include/fwk_log.h, framework/src/fwk_core.c, module/cmn700/src/mod_cmn700.c, module/dvfs/src/mod_dvfs.c, module/mhu/src/mod_mhu.c, module/optee/clock/src/mod_optee_clock.c, module/optee/reset/src/mod_optee_reset.c, module/power_domain/src/mod_power_domain.c, module/scmi/src/mod_scmi.c, module/scmi/src/mod_scmi_base.c, module/scmi_apcore/src/mod_scmi_apcore.c, module/scmi_clock/src/mod_scmi_clock.c, module/scmi_perf/src/mod_scmi_perf.c, module/scmi_perf/src/perf_plugins_handler.c, module/scmi_power_domain/src/mod_scmi_power_domain.c, module/scmi_reset_domain/src/mod_scmi_reset_domain.c, module/scmi_sensor/src/mod_scmi_sensor.c, module/scmi_system_power/src/mod_scmi_system_power.c, module/scmi_voltage_domain/src/mod_scmi_voltage_domain.c, module/sp805/src/mod_sp805.c, module/statistics/src/mod_stats.c, module/system_power/src/mod_system_power.c, module/timer/src/mod_timer.c, product/juno/module/juno_xrp7724/src/mod_juno_xrp7724.c, product/juno/src/juno_scmi_clock.c, product/optee-stm32mp1/module/stm32_pmic_regu/src/mod_stm32_pmic_regu.c, product/optee-stm32mp1/module/stm32_pwr_regu/src/mod_stm32_pwr_regu.c
This patchset adds `FWK_TRACE` functionality and includes
an example to use it.
It also renames `TRACE` to `DEBUG` because in further patches
a new functionallity for tracing will be introduced and having
the same name for both could cause confusion.
=> fwk: add FWK_TRACE

product/optee-fvp/fw/config_scmi_clock.c
Align SCMI clock init value with MOCK clock and system PLL which are enabled by default.
SCMI compliance test fails without this change.
=> product/optee-fvp: fix scmi clock init state

doc/code_rules.md
We want to use the proper Syntax Highlighting for C-like code blocks and that also align with what we have in code_style.md.
Change-Id: Icd3c2b1d8978b704cd02665275f9f6523c00a58f
Signed-off-by: Andrew Graham <andrew.graham@arm.com>
=> doc/code_rules: Replace block \code highlighters with ```c

module/power_domain/src/mod_power_domain.c
notify_warm_reset returns `false` when notifications are not enabled, while it should return an integer and not a boolean.
Return FWK_SUCCESS when framework notifications are not available instead.
Change-Id: Ib2519e07e9dcd648a8b608c5bcc77d0a81986e57
=> power_domain: Fix return status for notify_warm_reset

product/rdn2/scp_ramfw/config_cmn700.c, product/rdn2/scp_ramfw/config_pcie_integ_ctrl.c
Enable CMN and PCIe integration control configurations for memory regions of SoC expansion block that is connected to IO virtualization block #1 on RD-N2-Cfg2 platform. This will allow to enumerate the devices present in SoC expansion block on RD-N2-Cfg2 platform.
=> platform/rdn2: Enable soc expansion block on RD-N2-Cfg2

framework/src/fwk_arch.c, framework/src/fwk_core.c
This PR contains two patches to fix buffered logging issues. The first patch resolves incomplete logging when `SCP_ENABLE_SUB_SYSTEM_MODE` is enabled, while the second patch prevents the system from being suspended when there are elements in the output log buffer ready to be printed.
=> Fix buffered log output behaviour

product/morello/include/morello_sds.h, product/morello/module/morello_system/src/mod_morello_system.c
Populate plat_info structure with the silicon revision which is fetched from the SCP2PCC module.
Change-Id: I1168789630f85c25dc48364468e0bbd997391587
=> morello: Populate silicon revision in the SDS structure

.gitignore, doc/cmake_readme.md, docker/Dockerfile, docker/rootfs/usr/local/bin/dependencies, docker/rootfs/usr/local/bin/init, docker/rootfs/usr/local/bin/prepare_llvm
This patch fixes all outdated dependencies and broken links.
ArmClang compiler 6 is not longer provided in the Docker image, if it is required the compiler directory should be mounted as a volumen in the specified location in the documentation.
LLVM was updated to the latest supported version by the firmware with the instalation script that build the compiler-rt assets.
For the `dev` taget an user was created following the recomendations from Docker documentation.
Change-Id: I28bc940fefa754796e98f473bdb1f85bd13cc683
=> docker: fix dependencies and broken links

module/scmi_clock/test/mod_scmi_clock_unit_test.c
Instead of binding APIs invoke the message_handler directly. To remove unnecessary code and simplify the test.
Change-Id: Id440d4ca6d951877e78e74374f00877d78d8559c
=> scmi_clock/test: invoke the message_handler directly

debugger/src/cli/cli.c
After c15ff7e9505e3544daa4ac5329f302e536fe7acf
which removes the prepending carriage return from the drivers. It moves the responsibility of prepending carriage return to the user of the driver. This patch is adding this logic to the cli.
=> cli: Prepend carriage return to line feed

change_log.md
RDN2 platform fails to boot. As a consequence, a github issue is raised and a temporary workaround provided. This is mentioned in change_log.md within this patch.
=> scp: Update change_log for v2.12.0

Makefile.cmake
This patch addresses an issue where a reference was missing after renaming from `FWK_LOG_LEVEL_DEBUG` to `FWK_LOG_LEVEL_TRACE`. The fix ensures all references are properly updated.
Change-Id: Icf1ea1386bb9cbaf4f04b875d3194c5b18cda2bd
=> fwk: fix missing references for `FWK_LOG_LEVEL_TRACE`

module/scmi_clock/test/CMakeLists.txt, module/scmi_clock/test/config_scmi_clock.h, module/scmi_clock/test/mod_scmi_clock_unit_test.c, unit_test/CMakeLists.txt
This patch adds unit test for the state and reference counting check and update functions.
=> scmi_clock: add UT test cases

tools/ci_cmake.py
While running ci_cmake.py in case the host machine does not support docker inform the user.
Change-Id: I7ddd14b4074ca6d93c75f614e5fc474fe9c0494a
=> ci_cmake: Warn users when script runs w/o docker support

Makefile.cmake, framework/CMakeLists.txt, framework/include/fwk_log.h, framework/src/fwk_core.c, framework/src/fwk_delayed_resp.c, framework/src/fwk_module.c, framework/src/fwk_notification.c, module/isys_rom/src/mod_isys_rom.c, product/morello/module/morello_mcp_system/src/mod_morello_mcp_system.c, product/morello/module/morello_sensor/src/mod_morello_sensor.c, tools/cppcheck_suppress_list.txt
Add a new 'disabled' log level to the framework that allows for the framework to be ran without producing log messages. Includes fixes for the Morello platform that prevents CppCheck from flagging unused variables when log level is set to 'CRIT' and 'DISABLED' respectively.
=> Add "disabled" log level

unit_test/template/test/CMakeLists.txt, unit_test/template/test/config_template.h, unit_test/template/test/fwk_module_idx.h, unit_test/template/test/mod_template_unit_test.c, unit_test/user_guide.md
It's been some time since we introduced unit testing in the SCP-firmware project.
Even though the guidelines are pretty useful to get started, we want to simplify even further the adoption of unit testing for the contributors who may still not familiar with it.
Thus, we provide a template that can be used as a first copy-paste example which, along with the instructions, can provide a quick starter into unit testing development.
=> unit_test: Add template for Quick Start

product/n1sdp/module/n1sdp_system/src/mod_n1sdp_system.c
Commit 3980808137cf80f5be6a96b453ac9d3ed0f3c752 added support for N1SDP multichip configurations, using the struct n1sdp_multichip_info. Commit d2efba33e3b82398eea6b2ef344196b48940228c merged multichip information into a new structure, but did not remove the declaration of n1sdp_multichip_info. This commit removes the declaration.
Change-Id: I3b14f568c7884ea3cb140fb7f2052c4e4dfe0673
=> n1sdp: remove unused multichip info structure

product/morello/module/morello_system/src/mod_morello_system.c
Commit ee56f02cadf70726b2f2e869485a7b1bd2cec48e added the Morello system module, based on the N1SDP system module. This included a declaration of the struct morello_multichip_info, which was not used. This commit removes this unused declaration.
Change-Id: I24aebb19a138137c433dcafd5dff25ae8f187b8a
=> morello: Remove unused multichip info struct

module/cmn700/src/mod_cmn700.c
Adjust the address of SYSCACHE type region with chip address space offset while mapping the regions in CMN.
This change fixed the bug introduced in the previous change which wrongly maps local system cache address in remote chip's without adjusting it with chip address space.
Change-Id: Ic3b47200b1d1646b8d0e746f0ba55caf7b616c5f
=> cmn700: use offset adjusted address for remote chips

framework/include/fwk_io.h, framework/src/fwk_io.c, framework/src/fwk_log.c, module/pl011/src/mod_pl011.c, module/pl011/test/CMakeLists.txt, module/pl011/test/config_pl011.h, module/pl011/test/fwk_module_idx.h, module/pl011/test/mocks/.clang-format, module/pl011/test/mod_pl011_unit_test.c, tools/cppcheck_suppress_list.txt, unit_test/CMakeLists.txt
This PR introduces several improvements:
- Initial unit tests for `pl011` driver
- Simplified `mod_pl011_init_ctx` function
- Removed redundant code in `pl011` driver
- Enhanced handling of TX buffer full condition
- Introducing `fwk_io_putch_nowait` function in `fwk_io` module
=> Enhanced `pl011` driver with simplification and extended functionality for `fwk_io` module

product/synquacer/module/synquacer_system/src/synquacer_main.c
Current Trial Boot implementation for SynQuacer platform updates metadata on every boot even if the value is not changed. The metadata is stored in the NOR Flash, so updating NOR Flash should be minimized.
This commit checks the accept flag, then updates the metadata when the value is changed and needs to be updated.
=> product/synquacer: prevent metadata from being updated on every boot

Makefile.cmake
This change adds missing target info for fwk_test and mod_test in cmake help to inform user about these unit testing targets.
=> CMake: Add target info for fwk_test and mod_test in help

module/msys_rom/src/mod_msys_rom.c, product/n1sdp/module/n1sdp_mcp_system/src/mod_n1sdp_mcp_system.c, product/tc2/module/tc2_bl1/src/mod_tc2_bl1.c
Fix defects raised by the 'scp-tests-ci-all-log-levels' Jenkins Job in product/n1sdp, product/tc2, and morello when CPPcheck raises unused variable warnings when log level parameter is set to either 'DISABLED' or 'CRIT'.
=> Fix "all-log-level" defect

module/power_domain/src/mod_power_domain.c
pd->current_state is updated upon receiving a transition report; other state variables are not. This can be valid when the report results from a request. However, this won't be valid for non-requested transitions such as wakeup. Hence, update all state variables accordingly.
=> module/power_domain: Update all power state variables upon report

module/mhu3/src/mod_mhu3.c
In the mhu3_bind() function, the transport_api pointer variable is passed to the fwk_module_bind() instead of the pointer address. This causes an error when the framework bind function checks if the API pointer is NULL. This patch fixes this error.
Change-Id: I774b0ec5104232918b73602b54ce74a86617b185
=> module/mhu3: fix bind function

module/system_power/src/mod_system_power.c
Remove fwk_check that the element_count > 0, which prevents a system without PPUs from using the system_power module.
=> system_power: allow having 0 elements

tools/ci_cmake.py
Juno has two `PLATFORM_VARIANTS`, i.e. `BOARD` and `FVP`. These are updated in the ci_cmake.py file.
=> The platform variants for juno platform is updated for CI.

framework/src/fwk_io.c
`fwk_assert` calls  were removed to minimize assertions in the framework code, since they can be easily replaced by error handling. The reasons to do that are that the framework should be reliable enough, the debugging process of the framework should not rely on the users and the error handling can facilitate the usage of the framework.
Change-Id: Ib9c71580cb0c489b50a63d9fb5957ecf9459d212
=> fwk_io: Replace `fwk_assert` for error handling

module/mhu3/doc/mhu3.md, module/scmi_system_power_req/include/mod_scmi_system_power_req.h, module/smcf/doc/smcf.md
Trivial fixes for doxygen for SMCF, SCMI System Power and MHUv3.
=> Doxygen trivial fixes (SMCF, SCMI-SP, MHU3)

module/pl011/src/mod_pl011.c
During some refactoring, a2ab9889bab9 introduced a logical bug in the sanity check of the integer and fractional divisors. This can be seen with the trivial case of int divisor = 2 and frac divisor = 0 causing an assert.  Update the check to correctly reflect the comment, and HW spec/TRM.
=> pl011: incorrect assert when fractional divisor is zero

module/pcid/include/mod_pcid.h, module/pcid/src/mod_pcid.c, module/sid/include/mod_sid.h, module/sid/src/mod_sid.c, product/rdn1e1/src/config_sid.c, product/rdn2/src/config_sid.c, product/rdv1/src/config_sid.c, product/rdv1mc/src/config_sid.c, product/sgm775/src/config_sid.c, product/sgm776/src/config_sid.c
Certain peripherals have only a partial set of valid PID and CID
identification registers. On such peripherals, the PID and CID
register address offsets remain the same even though only a partial
set of registers are valid. Reading the invalid PID/CID registers
lead to a implementation specific behaviour. For example, such
reads could cause bus aborts.
For the supported platforms, allow the module configuration data to
specify the valid set of PID/CID registers to be compared. The valid
set of registers are represented as a bitmap.
Peripherals could implement a smaller set of PID/CID registers for its
identification and reading unimplemented registers could cause aborts.
So allow modules to specify a valid set of PID/CID register values
that have to be examined against a set of expected …
=> Allow a selected list of PID/CID registers to compare

product/morello/module/morello_sensor/src/mod_morello_sensor.c, product/morello/scp_ramfw_soc/Firmware.cmake
This change enables scmi-sensor module for Morello and implements an accessor method to retrieve the
sensor-related information provided via sensor module configuration.
Change-Id: Ic2905108c39a55b411d850217fa08a8652b87faa
=> product/morello: Add SCMI sensor management

module/smcf/CMakeLists.txt, module/smcf/include/smcf_utils.h, module/smcf/src/smcf_utils.c, module/smcf/test/CMakeLists.txt, module/smcf/test/smcf_utils/fwk_module_idx.h, module/smcf/test/smcf_utils/mod_smcf_utils.cmake, module/smcf/test/smcf_utils/smcf_utils_unit_test.c
Add a helper function to configure SMCF RAM based on SMCF header configuration and data size.
=> smcf_utils: Utility for helping with the configuration.

module/smcf/src/mgi.c, module/smcf/test/mgi/mgi_unit_test.c
This change fixes the enablement of start and end sample identifiers. Currently if start sample identifier is already enabled and then end identifier is also requested, it results in WRCFG.NUM_SAMPLE_ID to be written with an invalid value 0b11 whereas the expected value as per specification is 0b10 to enable both START and END sample identifiers in data header.
=> SMCF: Fix enablement of START and END sample identifiers in WRCFG

module/smcf/src/mgi.c, module/smcf/src/mgi_validate_header.h
This change added mgi_validate_header.h which has static asserts for each MGI field against its offsets based on the specification. So that any change that doesn't comply with the MGI specification can be traced down at the compilation itself.
=> SMCF: Add MGI validate header for MGI struct definition validation

module/ppu_v0/src/mod_ppu_v0.c, module/ppu_v1/src/mod_ppu_v1.c, tools/cppcheck_suppress_list.txt
After set power received, PPU report the current power state hardcoded without
any check the HW state.
Return the current power status if the set power return in successful
state otherwise get the current power status from direct reading HW.
Fix error messages logs by replacing [PD] by [PPU].
=> ppu power status

module/scmi_system_power_req/include/mod_scmi_system_power_req.h, module/scmi_system_power_req/src/mod_scmi_system_power_req.c, module/scmi_system_power_req/test/mod_scmi_system_power_req_unit_test.c
This change enables handling multiple elements in this module and also removes the use of events to handle the scmi messages and responses.
It also includes updates for the corresponding unit tests.
Change-Id: I5c91b8c36aeddc891f78daf11336467bf54da495
=> module/scmi_system_power_req: Enable multiple elements

module/thermal_mgmt/doc/thermal_mgmt.md, module/thermal_mgmt/include/mod_thermal_mgmt.h, module/thermal_mgmt/src/mod_thermal_mgmt.c, module/thermal_mgmt/test/mod_thermal_mgmt_unit_test.c, product/totalcompute/tc2/scp_ramfw/config_thermal_mgmt.c
Add cold_state_power configuration to be used instead of TDP when
temperature is below `switch_on_temperature`.
To accommodate the cases where it's possible not to limit or use
different limits than TDP for the distributable power when
the system is "cold."
Configure cold state power of thermal management in TC2.
=> Add cold-state power for thermal management

debugger/src/cli/cli_commands_core.c
This allows us to have a working reset command in the debugger CLI by creating our own reset_sys_f function
=> cli: changed reset command to weak symbol to allow override

framework/src/fwk_log.c, tools/cppcheck_suppress_list.txt
This allows creating a custom banner instead of the default ones provided by the log framework.
Usage is by adding the following in fmw_log.h:
```
#define FMW_LOG_CUSTOM_BANNER
#define FMW_LOG_CUSTOM_BANNER_STRING "custom banner string"
```
=> fwk_log: Add option for custom banner

doc/cmake_readme.md, doc/framework.md, framework/CMakeLists.txt, framework/include/fwk_dlist.h, framework/include/fwk_list.h, framework/include/fwk_slist.h, framework/src/fwk_core.c, framework/src/fwk_dlist.c, framework/src/fwk_slist.c, tools/cppcheck_suppress_list.txt
Enable queue monitors and tracing the maximum queue elements as a watermark for both isr and event queues.
To enable queue monitor and watermark for tracing, `SCP_ENABLE_FWK_EVENT_WATERMARK_TRACING` shall be true.
=> fwk_list: Add a watermark to monitor list max sizes

product/totalcompute/tc1/scp_ramfw/CMakeLists.txt, product/totalcompute/tc1/scp_ramfw/Firmware.cmake, product/totalcompute/tc2/scp_ramfw/CMakeLists.txt, product/totalcompute/tc2/scp_ramfw/Firmware.cmake
Fix the CMake scripts to correctly include the Resource Permissions module in the ramfw target.
For both TC1 & TC2.
=> TCx: Fix Resource Permissions inclusion in build

product/rdn2/include/system_pik.h
IONCICLK_CTRL/IONCICLK_DIV1 were incorrectly marked as RO and WO, which breaks the read/modify/write behavior in mod_pik_clock.c.  Also updated TCUx_CLK_ENABLE and NCIx_CLK_ENABLE R/W attributes, even though not yet referened in the existing SW.
=> product/rdn2: IONCICLK ctrl/div and TCU/IONCI clock enable should be RW

interface/amu/doc/amu.md, interface/amu/interface_amu.h
Add AMU interface definition.
The interface introduces an API to get the `AMU` counters of CPUs.
The definition of `AMU` interface to be implemented by multiple
drivers as counters access from SCP differs across platforms.
=> interface: `AMU`

.clang-format, doc/build_system.md
The documentation for the build system has been updated to include information about interfaces. Interfaces provide a common set of functionalities and define APIs and data structures for modules to implement specific features. The updated documentation explains the folder structure and usage of interfaces.
Change-Id: Ib9965fb23b46fd974f777b73c60dc25af4da1e74
=> doc: add interface documentation

module/cdns_i2c/src/mod_cdns_i2c.c, product/morello/include/morello_sds.h, product/morello/module/morello_scp2pcc/include/mod_morello_scp2pcc.h, product/morello/module/morello_system/src/mod_morello_system.c, product/morello/scp_ramfw_soc/config_sds.c, tools/cppcheck_suppress_list.txt
Adds a firmware information structure to the SDS region on Morello, containing Morello-specific SCP, PCC, and MCC version information. This is to provide access to this versioning in further firmware stages. Additional commit resolves I2C issues where multiple SCP2PCC requests are made in succession, such as when fetching the PCC and MCC versions.
=> morello: Add firmware version information to SDS

arch/arm/arm-m/include/arch_helpers.h, arch/arm/armv8-a/include/arch_helpers.h
The implementation for arch_interrupts_disable is incrementing the nest counter outside the critical section. This can lead to unexpected behavior because there is no guarantee the counter will be incremented atomically.
This change first aquires the critical section (by disabling irqs) then increments the counter thus guarantees the counter will be incremented atomically.
=> increment nest counter inside critical section

product/morello/module/morello_system/CMakeLists.txt, product/morello/module/morello_system/include/mod_morello_system.h, product/morello/module/morello_system/src/mod_morello_system.c
Currently, on SCP, there is no way for users to get CPU temperature values during or after boot. This change will show reference temperature values during boot, so that the alarm or shutdown threshold does not come as a surprise.
Change-Id: I6079a750d4aeaa7768784aee640919cf2faa76b0
=> morello: print the temperature sensor values during boot

interface/cmn/doc/cmn.md, interface/cmn/interface_cmn.h, module/cmn700/CMakeLists.txt, module/cmn700/include/mod_cmn700.h, module/cmn700/src/mod_cmn700.c
CMN module drivers can change between platforms; this makes it challenging to write a generic module that uses CMN APIs to map regions during runtime.
Add a generic API interface that CMN modules use to define their APIs and use the module ID provided by the platform configuration to bind to the correct CMN module.
=> interface/cmn: Add a interface for CMN drivers

module/cmn700/src/cmn700.c
Fix the logical error in the cmn700 address alignment check. Due to the logical error, the check only failed if the address and size were unaligned.
Updated the logic to allow it to fail if either value is unaligned. Also fixed the wrong address mask calculation.
=> cmn700: fix address and size alignment check.

product/morello/module/dmc_bing/src/mod_dmc_bing.c, product/n1sdp/module/n1sdp_dmc620/src/mod_n1sdp_dmc620.c, tools/cppcheck_suppress_list.txt
Currently, the SCP boot continues if the DDR4 training fails, the boot then later hangs when it reaches tf-a stage. These patches will halt the boot in SCP itself.
=> Halt SCP boot if DDR4 training fails for morello and n1sdp

module/scmi_sensor_req/test/mod_scmi_sensor_req_unit_test.c, module/smcf/test/smcf_data/smcf_data_unit_test.c
There are some variables unitilialized for testing resulting in unexpected behaviour.
This patch fixes that giving them a default `0` value to ensure that all bytes are zeroed.
Change-Id: I29265f415bd9f9b1462884da7bc97ef83f1581a0
=> fix/unit-test: add variable initialization

module/scmi_perf/src/mod_scmi_perf.c
Currently, when perf_prot_ops_process_events function returns successfully the scmi_perf_process_event function returns an error condition. Correct this behaviour so that the function does not return an error condition during successful case.
=> scmi_perf: Correct the return status of scmi_perf_process_event
