- contributing.md
Fix typo in the word "contributions".
Change-Id: I3051031a981bf0104b2b5a849a8e28090bcbd592
Signed-off-by: Filipe Rinaldi <filipe.rinaldi@arm.com>
> contributing.md: Fix typo

- Makefile
- framework/test/test_version.c
- readme.md
Update firmware version to v2.4 and update the readme
file accordingly.
Change-Id: Id619c1e0efa513a96c6c5ab6038ee1b76c0ad70d
> Update firmware version to v2.4

- readme.md
- user_guide.md
Change-Id: Id4f3902985ee54530318551bdad12f4fe6481981
> documentation: Various fixes and improvements

- doc/framework.md
- product/host/fw/firmware.mk
- product/n1sdp/mcp_ramfw/firmware.mk
- product/n1sdp/scp_ramfw/firmware.mk
- product/sgi575/mcp_romfw/firmware.mk
- product/sgi575/scp_ramfw/firmware.mk
- product/sgi575/scp_romfw/firmware.mk
- product/sgm775/scp_ramfw/firmware.mk
- product/sgm775/scp_romfw/firmware.mk
Change-Id: I7c7990674526c0ecb1cba7362bc8ceccce174639
> doc: Add comments describing the module pre-runtime phase

- .gitignore
- tools/build_system/doc.md
- tools/build_system/firmware.mk
- tools/check_spacing.py
- tools/check_tabs.py
Change-Id: I054a77d3295150c1e5445d430cabaad978e7e594
> build: Add support for binary modules

- tools/ci.py
Build sgi575 firmware with gcc/Arm Compiler 6 in
release/debug mode
Change-Id: I3605a260778b3f55b8f55e09c68fe24f03991758
> ci: Add sgi575 builds

- product/n1sdp/include/n1sdp_scp_mmap.h
- product/n1sdp/include/n1sdp_ssc.h
- product/n1sdp/mcp_ramfw/config_log.c
- product/n1sdp/module/n1sdp_system/include/mod_n1sdp_system.h
- product/n1sdp/module/n1sdp_system/src/mod_n1sdp_system.c
- product/n1sdp/scp_ramfw/config_armv7m_mpu.c
- product/n1sdp/scp_ramfw/config_log.c
- product/n1sdp/scp_ramfw/config_ppu_v0.c
Misc updates for the AP Firmware copy to the SRAM ,and the baudrate alignment
> Deepan02 arm n1sdp ap fw updates

- product/clark/scp_ramfw/config_sds.c
- product/n1sdp/scp_ramfw/config_sds.c
- product/sgi575/scp_ramfw/config_sds.c
Change-Id: Ie6901be527ef2053cbe95dd6f47a29dec88aa7ca
> misc: Remove remaining instances of MODE_DEBUG

- framework/src/fwk_dlist.c
- framework/src/fwk_multi_thread.c
- framework/src/fwk_slist.c
- module/cmn600/src/mod_cmn600.c
- module/ppu_v0/src/mod_ppu_v0.c
- module/system_power/src/mod_system_power.c
- product/clark/scp_ramfw/config_power_domain.c
- product/sgi575/scp_ramfw/config_power_domain.c
- product/sgm775/scp_ramfw/config_power_domain.c
This PR fixes various recently-identified bugs to:
- The framework
- The SGx platforms
- The cmn600, system_power and ppu_v0 modules
> Miscellaneous bugfixes

- module/smt/src/mod_smt.c
Change-Id: I7e7108be6bae3d5489888746ae58da7bc00035ab
> smt: Add logging on mailbox ownership error

- module/system_power/include/mod_system_power.h
Change-Id: I8060024e45a187afacdc70f9f39c9083f4cce71c
> system_power: Add API definition guard

- product/n1sdp/scp_ramfw/config_css_clock.c
Change-Id: Id1e6e069bb4cb253f7f000b80d6045873f4189dc
> n1sdp: fix cluster 1 cpu clock source in css_clock config file

- module/system_power/include/mod_system_power.h
- module/system_power/src/mod_system_power.c
- product/n1sdp/scp_ramfw/config_system_power.c
- product/rdn1e1/scp_ramfw/config_system_power.c
- product/sgi575/scp_ramfw/config_system_power.c
- product/sgm775/scp_ramfw/config_system_power.c
Improve system_power management by introducing platform interrupts and enabling a configurable number of system PPUs.
> System Power

- product/n1sdp/module/n1sdp_flash/include/mod_n1sdp_flash.h
- product/n1sdp/module/n1sdp_pll/include/mod_n1sdp_pll.h
- product/sgm775/module/sgm775_ddr_phy500/include/mod_sgm775_ddr_phy500.h
- product/sgm775/module/sgm775_dmc500/include/mod_sgm775_dmc500.h
Change-Id: Ia0228b3d436b5053b74c9e3f629719b927e17f51
> doc: Fix various documentation module grouping

- module/power_domain/src/mod_power_domain.c
- module/scmi/src/mod_scmi.c
Fix build issue when !BUILD_HAS_NOTIFICATION.
> Fix scmi & power_domain against `!BUILD_HAS_NOTIFICATION`

- framework/include/fwk_thread.h
- framework/src/fwk_thread.c
- module/clock/include/mod_clock.h
- module/clock/src/clock.h
- module/clock/src/mod_clock.c
- module/scmi_clock/include/internal/scmi_clock.h
- module/scmi_clock/src/mod_scmi_clock.c
This PR adds support to clock module and scmi_clock module for handling deferred requests
> Clocks - handle deferred responses

- module/psu/src/mod_psu.c
This PR fixes a couple of bugs identified in the recent asynchronous PSU support.
> PSU bugfixes

- module/clock/include/mod_clock.h
- module/clock/src/mod_clock.c
Minor fixes & improvements for the clock module.
> Clock: minor fixes & improvements

- arch/src/arm_nvic.c
- doc/code_rules.md
- framework/test/fwk_test.c
- framework/test/test_fwk_list_insert.c
- framework/test/test_fwk_multi_thread_common_thread.c
- framework/test/test_fwk_multi_thread_put_event.c
- module/clock/src/mod_clock.c
- module/cmn600/src/cmn600.c
- module/mhu2/src/mod_mhu2.c
- module/power_domain/src/mod_power_domain.c
- module/ppu_v0/src/mod_ppu_v0.c
- module/ppu_v1/src/mod_ppu_v1.c
- module/sensor/src/mod_sensor.c
- product/n1sdp/module/n1sdp_ddr_phy/src/mod_n1sdp_ddr_phy.c
- product/n1sdp/module/n1sdp_pll/src/mod_n1sdp_pll.c
- product/n1sdp/module/n1sdp_remote_pd/src/mod_n1sdp_remote_pd.c
- tools/banned_api.lst
- tools/check_api.py
- tools/cppcheck_suppress_list.txt
This PR fixes mistakes discovered by Cppcheck static analyzer and introduces a files for performing static analysis in the Continuous Integration process.
> Ci static analysis

- framework/include/fwk_notification.h
- framework/src/fwk_notification.c
- framework/test/test_fwk_notification.c
- module/clock/src/mod_clock.c
- module/msys_rom/src/mod_msys_rom.c
- module/power_domain/src/mod_power_domain.c
- module/scmi/src/mod_scmi.c
- module/smt/src/mod_smt.c
- module/timer/include/mod_timer.h
- module/timer/src/mod_timer.c
- product/juno/module/juno_ddr_phy400/src/mod_juno_ddr_phy400.c
- product/juno/module/juno_dmc400/src/mod_juno_dmc400.c
- product/juno/module/juno_ram/src/mod_juno_ram.c
- product/juno/module/juno_rom/src/mod_juno_rom.c
This PR adds some patches for:
-juno: Add low-power mode for DRR
-modules: Fix timer alarm_stop
-fwk: Expand notifications with provided source_id
> juno: Various fixes and support for system suspend

- module/system_power/src/mod_system_power.c
System_power module uses drivers that are defined by
the power_domain module. These drivers can optionally
implement the shutdown function which is called during
the shutdown procedure.
This patch extends the shutdown procedure within this
module so the shutdown function in the drivers will be
called, if provided.
Change-Id: I8c02809ee5669f3651a19fa7b69a9c084521749e
> system_power: Use PPU shutdown handlers

- product/juno/module/juno_hdlcd/src/mod_juno_hdlcd.c
- product/juno/scp_ramfw/config_juno_adc.c
- product/juno/scp_ramfw/config_sensor.c
> Juno minor fixes

- product/juno/module/juno_xrp7724/src/mod_juno_xrp7724.c
This patch introduces a cache for the voltage value for each PSU device
in order to prevent the device from doing I2C transmissions and reading
the voltage if it is already cached or set to the requested value.
Change-Id: I812b2b442069a2f4929d801c79989aea75a265f9
> juno/xrp7724: Cache voltage value to save I2C transmissions

- module/dvfs/doc/module_dvfs_architecture.md
This patch documents the DVFS architecture.
Change-Id: Ied975adb95a093a00ee23ca215caa7a646d96304
> DVFS: Document DVFS architecture

- module/clock/src/mod_clock.c
- module/i2c/src/mod_i2c.c
> i2c/clock: minor fixes

- module/pl011/src/mod_pl011.c
- module/power_domain/include/mod_power_domain.h
- module/power_domain/src/mod_power_domain.c
- module/scmi_system_power/src/mod_scmi_system_power.c
- product/juno/module/juno_system/src/mod_juno_system.c
- product/juno/module/juno_xrp7724/include/mod_juno_xrp7724.h
- product/juno/module/juno_xrp7724/src/mod_juno_xrp7724.c
This PR contains enhancements in core modules to correctly deal with reboot/shutdown and updates in juno-specific modules to execute reboot/shutdown.
> Juno shutdown

- product/rddaniel/src/config_pl011.c
- tools/ci.py
Along with the pl011 config data update, add rddaniel platform to the CI build test.
> Update config pl011 config data for RD-Daniel platform

- product/n1sdp/module/n1sdp_dmc620/src/dimm_spd.c
Change-Id: I183b45bef4e3a344f85ac13f896d989b4e14fce0
> n1sdp: Fix precision loss in floating point calculation

- product/juno/module/juno_thermal/src/mod_juno_thermal.c
Power state transitions for SYSTOP need to be
received to stop the alarm when SYSTOP is down and
restart the alarm when SYSTOP is back on.
This will prevent the thermal protection attempting
to access resources not available when SYSTOP is down.
Change-Id: I2bfdb39f4f0679590f8abb3f147dab2ac5618cb3
> juno/thermal: Add notifications for SYSTOP

- product/juno/module/juno_system/src/mod_juno_system.c
The Juno System module is currently returning FWK_E_PARAM from its
notification handler in cases where it should be returning FWK_SUCCESS.
This commit fixes this issue and simplifies the notification handling
logic.
Change-Id: If50906186603f6f119f9c18687ef664947ebf0b4
> juno: Fix juno_system notification handler

- user_guide.md
The tools used to test the firmware internally have been updated, and so
the documentation has been updated to reflect the new version
requirements.
Change-Id: If5c9e9a9cfd614be6521d25bb0cb55b4e585615c
> user_guide: Update tool version requirements

- change_log.md
- readme.md
- user_guide.md
This patch adds the release notes for v2.6.0.
Change-Id: Idfd5bde6c775328463ed2c8cf4aef303a75cfd45
> scp_v2.6: Release notes for SCP firmware v2.6.0

- Makefile
- framework/test/test_version.c
Update release version to v2.6.0.
Change-Id: I190d1552b57880164939ee4f08ef429f1d542b15
> Update firmware version to v2.6.0

- product/juno/scp_ramfw/config_dvfs.c
This PR contains minor fixes for the dvfs configuration for Juno
> juno: dvfs minor fixes

- user_guide.md
Following internal out-of-box testing feedback, the user guide has been
updated to clarify certain steps.
Change-Id: Ib5a69d599a53f14d3a21578ba61cfde1e76b6ef3
> doc: Update user guide

- module/scmi/include/mod_scmi.h
- module/scmi/src/mod_scmi.c
- module/smt/include/mod_smt.h
- module/smt/src/mod_smt.c
Adds support non-SCMI SMT messages
> SMT-SCMI decoupling 

- product/rdn1e1/include/scp_system_mmap.h
- product/sgi575/include/scp_system_mmap.h
This pull update the PLL base address based on the new RoS (Rest of the System) specification
> SGI-575 and RD-N1-Edge pll change

- module/scmi/src/mod_scmi.c
Change-Id: I85376346c8dab91a28d0ec469a09fff7cee0277a
> scmi: Normalize SCMI log messages

- .github/CODEOWNERS
- maintainers.md
Change-Id: I183e41d0dc4462db77b27ee2986f084e7ab1a089
> misc: Update maintainers list

- module/clock/include/mod_clock.h
- module/scmi_clock/include/mod_scmi_clock.h
- module/scmi_clock/src/mod_scmi_clock.c
- module/scmi_perf/include/mod_scmi_perf.h
- module/scmi_perf/src/mod_scmi_perf.c
- module/scmi_power_domain/include/mod_scmi_power_domain.h
- module/scmi_power_domain/src/mod_scmi_power_domain.c
- module/scmi_system_power/include/mod_scmi_system_power.h
- module/scmi_system_power/src/mod_scmi_system_power.c
- product/juno/scp_ramfw/firmware.mk
- product/juno/src/juno_scmi_clock.c
> SCMI: Add Protocol Policy Handlers

- module/dvfs/include/mod_dvfs.h
- module/dvfs/src/mod_dvfs.c
- module/scmi_perf/include/mod_scmi_perf.h
- module/scmi_perf/src/mod_scmi_perf.c
- module/statistics/include/mod_stats.h
- module/statistics/src/Makefile
- module/statistics/src/mod_stats.c
- product/juno/include/juno_alarm_idx.h
- product/juno/include/software_mmap.h
- product/juno/scp_ramfw/config_scmi_perf.c
- product/juno/scp_ramfw/config_stats.c
- product/juno/scp_ramfw/firmware.mk
- tools/build_system/doc.md
- tools/build_system/firmware.mk
- tools/build_system/rules.mk
The performance and power statistics support.
> Topic/ll/rebase 03072020/scmi perf stats

- module/scmi_perf/src/mod_scmi_perf.c
- module/scmi_power_domain/include/internal/scmi_power_domain.h
- module/scmi_power_domain/src/mod_scmi_power_domain.c
> Assorted bug fixes

- module/scmi_system_power/include/mod_scmi_system_power.h
- module/scmi_system_power/src/mod_scmi_system_power.c
This change allows each platform to define a policy for handling
graceful requests.
Change-Id: I3dc5ed0cf57c859a2a73a2a9a0f8ffc3bd311031
> scmi_system_power: Move the graceful request into the policy function.

- module/dvfs/src/mod_dvfs.c
- module/scmi_perf/src/mod_scmi_perf.c
- product/juno/scp_ramfw/firmware.mk
> SCMI notifications/fast channels code should be conditionally built into the firmware

- tools/gen_module_code.py
The gen_module rule in rules.mk is marked as .PHONY, so make will
execute it whenever it is mentioned. This results in gen_module_code
being executed 64 times for a Juno build.
However in heavily parallel builds there's a good chance that
gen_module_code is writing a file whilst the compiler is reading it
because make also doesn't know what files are generated by
gen_module_code.
The correct fix is to adjust the Makefiles so that the dependencies are
correct but this isn't trivial, so band-aid the problem by atomically
writing the generated files.
Change-Id: I82d44f9ea6537a91002e1f80de8861d208571630
Signed-off-by: Ross Burton <ross.burton@arm.com>
> tools/gen_module_code: atomically rewrite the generated files

- module/power_domain/src/mod_power_domain.c
This patch implements a validation check such that when the
get_last_core_pd_id() function is called by the driver, the
module returns an error if the system is not performing
system_supend.
Change-Id: Ied3a2f17b2fb471933232c8209e4d3048c4a1e8b
> power_domain: Add check for get_last_core_pd_id

- framework/src/fwk_thread.c
> fwk: Minor optimisations for single-threaded event handler

- module/power_domain/src/mod_power_domain.c
> module: power domain: add a missing return

- change_log.md
- readme.md
Change-Id: Ifb167c12f4140f8e50220af93a7852af01af5904
> misc: Update link to SCMI spec and minor cosmetics

- Makefile
Change-Id: Ie9d6dff2a443b5231803d35e6b584879e70e91b9
> scp: Update firmware version to 2.7.0

- product/n1sdp/module/n1sdp_pcie/src/mod_n1sdp_pcie.c
Set CCIX speed to GEN3 to work with interposer C2C setup
In this use case set downstream/upstream port transmitter
preset value to 4.
Signed-off-by: Jagadeesh Ujja <jagadeesh.ujja@arm.com>
Change-Id: I635566574babbb7591b5bba97105f76f1f8e550a
> product/n1sdp: set CCIX speed to GEN3 to work with interposer C2C setup

- product/synquacer/include/fmw_io.h
- product/synquacer/module/f_uart3/src/mod_f_uart3.c
- product/synquacer/module/synquacer_rom/src/mod_synquacer_rom.c
- product/synquacer/scp_romfw/firmware.mk
This pull request includes the fixes to align with the latest SCP-firmware design.
> Synquacer fixes

- module/scmi/src/mod_scmi.c
In this change , when resource permission module is disabled if a
protocol is listed in the disabled protocols for PSCI agent then
this protocol couldn't be accessed by PSCI agent and SCMI_DENIED_ERROR
is returned.
Change-Id: Id35ba35628eabd9b7bca7bb48b7016f60155dcec
> mod_scmi : Deny access for PSCI agent for configured protocols

- framework/src/fwk_multi_thread.c
This patch implements some minor optimisations for the
fwk_thread_put_event critical code path.
Change-Id: I0ccf2e9e95be2059242786c735ecb597bd4b47e7
> fwk: Minor optimisation in MT fwk_thread_put_event

- product/rddaniel/scp_ramfw/config_pik_clock.c
- product/rddanielxlr/scp_ramfw/config_pik_clock.c
This PR fixes the issue reported in https://github.com/ARM-software/SCP-firmware/issues/342
> product/rddaniel&rddanielxlr: Minor fix in PIK clock config file.

- framework/include/fwk_id.h
- framework/include/fwk_module.h
- framework/include/fwk_signal.h
- framework/include/fwk_thread.h
- framework/include/internal/fwk_id.h
- framework/include/internal/fwk_multi_thread.h
- framework/include/internal/fwk_signal.h
- framework/src/fwk_id.c
- framework/src/fwk_multi_thread.c
- framework/src/fwk_thread.c
- framework/test/test_fwk_multi_thread_common_thread.c
- module/dvfs/src/mod_dvfs.c
> FWK: Add framework signals API

- framework/src/fwk_multi_thread.c
- framework/src/fwk_thread.c
- module/scmi_clock/src/mod_scmi_clock.c
- user_guide.md
This PR contains:
- minor update on user-guide
- bug fixing on scmi_clock clock_id
- improvements on the logging messages in fwk
> scmi_clock & fwk: Bugfixes and improvements

- .github/CODEOWNERS
- maintainers.md
Change-Id: Id76fb0baf06d406dddb7ecd7c74b2da7a5751be6
> scp: Update maintainers and codeowners

- module/dvfs/doc/module_dvfs_architecture.md
- module/dvfs/src/mod_dvfs.c
- module/scmi_perf/src/mod_scmi_perf.c
- tools/build_system/doc.md
This PR contains:
- minor fixes for dvfs module
- minor fixes for documentation
> Dvfs & doc minor fixes

- Makefile.cmake
- doc/cmake_readme.md
- readme.md
- tools/check_spacing.py
- tools/check_tabs.py
- tools/ci_cmake.py
This PR is a part of ongoing CMake patches. This adds documentation related to building SCP firmware using cmake and misc tools update.
> Cmake tools docs

- doc/cmake_readme.md
Change-Id: I04b20aacd18378b728b8dbfd0e605f42ad78e50d
> cmake: remove duplicate home directry from documentation

- module/scmi_power_domain/include/internal/scmi_power_domain.h
- module/scmi_sensor/include/internal/scmi_sensor.h
- user_guide.md
This PR brings updated to the user guide and minor doxygen fixes
> User guide update

- module/dvfs/src/mod_dvfs.c
- module/scmi/src/mod_scmi.c
- module/scmi_perf/src/mod_scmi_perf.c
- product/tc0/scp_ramfw/config_dvfs.c
This PR contains minor clean-up and indentation fixes, along with a minor improvement for saving space in SCMI module for logs.
> Miscellaneous tidy-up patches

- Gemfile.lock
This patch udpdates several dependencies in Gemfile.lock
Change-Id: I73790f1f49fcb770ebd4a4beb0b4d7fb56d29d29
> Gemfile.lock: dependencies update

- module/psu/src/mod_psu.c
- module/sds/src/mod_sds.c
- module/smt/src/mod_smt.c
This PR contains some minor bug fixes and cosmetic improvements. They were detected during the MISRA 10.3 defects PR, for the module and framework files.
> Ancillary Bug Fixes 

- arch/arm/armv7-m/src/arch_nvic.c
- product/juno/include/fmw_cmsis.h
- product/morello/include/fmw_cmsis_mcp.h
- product/morello/include/fmw_cmsis_scp.h
- product/n1sdp/include/fmw_cmsis_mcp.h
- product/n1sdp/include/fmw_cmsis_scp.h
- product/rdn1e1/include/fmw_cmsis_mcp.h
- product/rdn1e1/include/fmw_cmsis_scp.h
- product/rdn2/include/fmw_cmsis.h
- product/rdv1/include/fmw_cmsis.h
- product/rdv1mc/include/fmw_cmsis.h
- product/sgi575/include/fmw_cmsis_mcp.h
- product/sgi575/include/fmw_cmsis_scp.h
- product/sgm775/include/fmw_cmsis.h
- product/sgm776/include/fmw_cmsis.h
- product/synquacer/include/fmw_cmsis.h
- product/tc0/include/fmw_cmsis.h
This PR is meant to replace pull/492.
This includes IRQn_Type fix for all platforms
> Resolve IRQ overflows

- arch/arm/armv7-m/include/arch_helpers.h
- arch/arm/armv8-a/include/arch_helpers.h
- arch/none/host/include/arch_helpers.h
- framework/CMakeLists.txt
- framework/include/fwk_id.h
- framework/include/fwk_interrupt.h
- framework/src/fwk_id.c
- framework/src/fwk_interrupt.c
- framework/test/arch_helpers.h
- framework/test/test_fwk_interrupt.c
This pull request contains the changes which may improve runtime performance of some use cases such as SCMI requests.
The focus of the improvement is reduce the function call overhead of some of the functions which gets executed very frequently at the runtime.
> SCP Firmware runtime performance optimizations

- product/morello/module/cmn_skeena/include/mod_cmn_skeena.h
- product/morello/module/cmn_skeena/src/mod_cmn_skeena.c
This patch series introduces additional functionality and some fixes for CMN-Skeena module
> morello: Changes for CMN-Skeena module

- module/resource_perms/include/mod_resource_perms.h
- module/resource_perms/src/mod_resource_perms.c
- module/scmi/src/mod_scmi.c
- module/scmi_perf/src/mod_scmi_perf.c
This PR contains a fix for mod_resource_perms and some MISRA C fixes on modules on resource permissions enabled sections.
> Misra resource permissions fixes

- arch/arm/armv7-m/src/arch_exceptions.c
- arch/arm/armv7-m/src/arch_nvic.c
- framework/src/fwk_id.c
- framework/src/fwk_log.c
- framework/src/fwk_mm.c
- framework/src/fwk_module.c
- framework/src/fwk_notification.c
- framework/src/fwk_ring.c
- framework/src/fwk_thread.c
- framework/src/fwk_time.c
i want to push these 3 patch to main repo.
> Misra fixes for arch & fwk

- product/synquacer/module/ppu_v0_synquacer/src/mod_ppu_v0.c
This commit adds the shutdown handler in ppu_v0_synquacer
module to do the different handling from normal cpu core
off process.
Without this commit, arm-systemready IR BSA test fails
because cpu core poweroff process sometimes fails.
Change-Id: I6c4bbc7eeff96b9849ed5392663086622f32373e
> synquacer: add shutdown handler in ppu_v0_synquacer module

- arch/arm/armv8-a/include/arch_helpers.h
- arch/arm/armv8-a/src/arch_gic.c
- arch/arm/armv8-a/src/arch_libc.c
- arch/arm/armv8-a/src/arch_mm.c
- framework/src/fwk_id.c
- framework/src/fwk_module.c
- framework/src/fwk_multi_thread.c
- module/dvfs/src/mod_dvfs.c
- module/i2c/src/mod_i2c.c
- module/power_domain/src/mod_power_domain.c
- module/power_domain/src/power_domain_utils.c
- module/psu/src/mod_psu.c
- module/reset_domain/src/mod_reset_domain.c
- module/scmi/src/mod_scmi.c
- module/scmi_apcore/src/mod_scmi_apcore.c
- module/scmi_clock/src/mod_scmi_clock.c
- module/scmi_perf/src/mod_scmi_perf.c
- module/scmi_power_domain/src/mod_scmi_power_domain.c
- module/scmi_reset_domain/src/mod_scmi_reset_domain.c
- module/scmi_sensor/src/mod_scmi_sensor.c
- module/scmi_system_power/src/mod_scmi_system_power.c
- module/sds/src/mod_sds.c
- module/sensor/src/mod_sensor.c
- module/smt/src/mod_smt.c
MISRA 10.3 defects relating to files detected with v8-A based products are addressed within these patches.
> Misra10.3 V8-A

- framework/src/fwk_io.c
- framework/src/fwk_module.c
- module/css_clock/src/mod_css_clock.c
- module/pik_clock/src/mod_pik_clock.c
- module/system_pll/src/mod_system_pll.c
This PR contains some improvements on 3 modules and for the framework.
The changes are targeting readability and code-size.
> Fwk & module improvements

- product/sgi575/include/mcp_software_mmap.h
- product/sgi575/include/mcp_system_mmap_mcp.h
- product/sgi575/include/rd_alarm_idx.h
- product/sgi575/mcp_ramfw/CMakeLists.txt
- product/sgi575/mcp_ramfw/Firmware.cmake
- product/sgi575/mcp_ramfw/Toolchain-ArmClang.cmake
- product/sgi575/mcp_ramfw/Toolchain-GNU.cmake
- product/sgi575/mcp_ramfw/config_armv7m_mpu.c
- product/sgi575/mcp_ramfw/config_clock.c
- product/sgi575/mcp_ramfw/config_debugger_cli.c
- product/sgi575/mcp_ramfw/config_gtimer.c
- product/sgi575/mcp_ramfw/config_pl011.c
- product/sgi575/mcp_ramfw/config_timer.c
- product/sgi575/mcp_ramfw/firmware.mk
- product/sgi575/mcp_ramfw/fmw_cmsis.h
- product/sgi575/mcp_ramfw/fmw_memory.h
- product/sgi575/mcp_ramfw/fmw_notification.h
- product/sgi575/mcp_romfw/CMakeLists.txt
- product/sgi575/mcp_romfw/Firmware.cmake
- product/sgi575/mcp_romfw/config_bootloader.c
- product/sgi575/module/mcp_platform/CMakeLists.txt
- product/sgi575/module/mcp_platform/Module.cmake
- product/sgi575/module/mcp_platform/src/Makefile
- product/sgi575/module/mcp_platform/src/mod_mcp_platform.c
- product/sgi575/product.mk
This patch series adds mcp ramfw support for sgi575 platform.
> Sgi575 mcpramfw

- product/rdn1e1/include/mcp_software_mmap.h
- product/rdn1e1/include/mcp_system_mmap_mcp.h
- product/rdn1e1/include/rd_alarm_idx.h
- product/rdn1e1/mcp_ramfw/CMakeLists.txt
- product/rdn1e1/mcp_ramfw/Firmware.cmake
- product/rdn1e1/mcp_ramfw/Toolchain-ArmClang.cmake
- product/rdn1e1/mcp_ramfw/Toolchain-GNU.cmake
- product/rdn1e1/mcp_ramfw/config_armv7m_mpu.c
- product/rdn1e1/mcp_ramfw/config_clock.c
- product/rdn1e1/mcp_ramfw/config_debugger_cli.c
- product/rdn1e1/mcp_ramfw/config_gtimer.c
- product/rdn1e1/mcp_ramfw/config_pl011.c
- product/rdn1e1/mcp_ramfw/config_timer.c
- product/rdn1e1/mcp_ramfw/firmware.mk
- product/rdn1e1/mcp_ramfw/fmw_cmsis.h
- product/rdn1e1/mcp_ramfw/fmw_memory.h
- product/rdn1e1/mcp_ramfw/fmw_notification.h
- product/rdn1e1/mcp_romfw/CMakeLists.txt
- product/rdn1e1/mcp_romfw/Firmware.cmake
- product/rdn1e1/mcp_romfw/config_bootloader.c
- product/rdn1e1/module/mcp_platform/CMakeLists.txt
- product/rdn1e1/module/mcp_platform/Module.cmake
- product/rdn1e1/module/mcp_platform/src/Makefile
- product/rdn1e1/module/mcp_platform/src/mod_mcp_platform.c
- product/rdn1e1/product.mk
This patch series adds mcp ramfw support for rdn1edge platform.
> Rdn1edge mcpramfw

- framework/src/fwk_id.c
- framework/src/fwk_status.c
- module/scmi/src/mod_scmi.c
- module/scmi_clock/src/mod_scmi_clock.c
- module/scmi_perf/src/mod_scmi_perf.c
- module/scmi_power_domain/src/mod_scmi_power_domain.c
- module/scmi_sensor/src/mod_scmi_sensor.c
- module/scmi_system_power/src/mod_scmi_system_power.c
These patches include MISRA 9.5 defects being addressed within scmi and framework files.
> Misra fixes for scmi & fwk

- readme.md
A Security issues reporting section is added to the Readme file.
This section consists of point of contact to report the security
issues and a link to the Arm Developer website in case more
information is needed by the viewer.
Change-Id: I86afcce34836dffe367486c99e01cc4a94d3b900
> readme.md: Add Security issue reporting

- module/power_domain/src/mod_power_domain.c
- module/scmi_perf/src/mod_scmi_perf.c
Some of MISRA defects for rules 15.6 & 11.9 were left behind.
This PR aims to address those.
> Misra fixes (15.6 & 11.9)

- module/scmi_perf/src/mod_scmi_perf.c
- product/juno/scp_ramfw/config_resource_perms.c
More 10.3 MISRA defects addressed within these two patches
> Further Misra 10.3 Defects

- docker/Dockerfile
- maintainers.md
- module/mpmm/doc/module_mpmm.md
- module/mpmm/include/mod_mpmm.h
This PR brings minor fixes for the maintainers' list, doxygen doc fixes for MPMM and dockerfile typos fixes.
> Miscellaneous (maintainers, doxygen, dockerfile)

- doc/code_style.md
- tools/check_copyright.py
I propose to update the copyright checker:
- to check only for changed files to have up-to-date copyright headers
- to add CMake files being checked as well
> Changes to the copyright checker

- arch/arm/armv7-m/src/arch_nvic.c
- arch/arm/src/arch_mm.c
- framework/include/internal/fwk_module.h
- framework/src/fwk_module.c
- framework/src/fwk_multi_thread.c
- framework/test/test_fwk_multi_thread_common_thread.c
- framework/test/test_fwk_multi_thread_create.c
- framework/test/test_fwk_multi_thread_init.c
- framework/test/test_fwk_multi_thread_put_event.c
- framework/test/test_fwk_multi_thread_util.c
- framework/test/test_fwk_notification.c
- framework/test/test_fwk_thread.c
- module/scmi/src/mod_scmi.c
- module/scmi_clock/include/internal/scmi_clock.h
- module/scmi_clock/src/mod_scmi_clock.c
- module/scmi_perf/src/mod_scmi_perf.c
- module/scmi_power_domain/src/mod_scmi_power_domain.c
- module/scmi_sensor/src/mod_scmi_sensor.c
- module/scmi_system_power/src/mod_scmi_system_power.c
Fix violation of required MISRA 5.7
> misrarules 5 7

- module/dvfs/src/mod_dvfs.c
- module/gtimer/src/mod_gtimer.c
- module/mhu/src/mod_mhu.c
- module/mock_psu/src/mod_mock_psu.c
- module/pl011/src/mod_pl011.c
- module/power_domain/src/mod_power_domain.c
- module/psu/src/mod_psu.c
- module/sensor/src/mod_sensor.c
- module/sensor/src/sensor.h
- module/smt/src/mod_smt.c
- module/system_power/src/mod_system_power.c
- module/timer/src/mod_timer.c
Some variable had same name as type.
Change variable name or type name to resolve conflict.
Co-authored-by: Tomás Agustín González Orlando <tomasagustin.gonzalezorlando@arm.com>
Signed-off-by: Tuvshinzaya Erdenekhuu <tuvshinzaya.erdenekhuu@arm.com>
Change-Id: I2f6eec87b466b1e9ef2e2e27789777bc4f6e5731
> module: Fix violation of required MISRA 5.7

- doc/Doxyfile
- module/clock/src/clock_tree_management.c
This pull requests cleans up the remaining inclusive language violations.
Arm is committed to making the language we use inclusive, meaningful, and
respectful. This commit is part of the inclusive language refactoring series
where we replace offensive terminology with more inclusive ones.
> New inclusive changes

- module/resource_perms/src/mod_resource_perms.c
- module/scmi/src/mod_scmi.c
- module/statistics/src/mod_stats.c
A tag name shall be a unique identifier.
The tag shall be unique across all name spaces and translation units.
Change variable name to resolve conflict.
Change-Id: I375d0083a9dada01ba94702b0775ae5023dc4b1d
> module: Fix violations of required MISRA 5.7

- module/clock/src/mod_clock.c
- module/dvfs/src/mod_dvfs.c
- module/power_domain/include/mod_power_domain.h
- module/power_domain/src/mod_power_domain.c
- module/reset_domain/src/mod_reset_domain.c
- module/sensor/src/mod_sensor.c
Hi All,
As discussed, I'm splitting PR #524  in smaller ones. This PR is a subset of it which contains the compilation error
> Fix compilation without notification

- module/scmi_clock/src/mod_scmi_clock.c
Some scmi tests are failing when building with resource
permissions enabled for some platforms.
When trying to access an incorrect clock or sending an
invalid parameter, the NOT_FOUND or the INVALID_PARAMETER
returns are expected by the test instead of the DENIED error.
Fix the logic so that the first thing that each clock handler does
is check whether the requested clock is available and only then
check whether the correct permissions are given to operate on said
clock.
The disadvantage of this implementation is that every new handler
will need to make sure that permissions are satisfied, while
currently we only perform the permissions check before moving to
the respective handlers. However, placing this function call in the
message_handler would imply having to get the clock_id and …
> mod_scmi_clock: Fix Resource Permissions returned error

- maintainers.md
Update list with core & platform maintainers.
Change-Id: I7e492ab98b9972671d8e9a6afafdce94c2076734
> maintainers: Update list of maintainers

- tools/ci_cmake.py
`--skip-container` inline argument is introduced to skip
container execution when it is set.
This could be useful for developers who run locally the script
but wish to skip the container spawning to speed-up developing
and testing.
Change-Id: Ib44aea5953d6017a4bac4ac6dd5fd9fe91c21d2a
> ci_cmake: Add flag to skip container execution

- module/debugger_cli/src/mod_debugger_cli.c
The debugger cli uses an alarm that periodically read a character from UART
to check if ctrl+E was pressed. However, the alarm is still being called
when the CLI is opened - which causes the CLI to occasionally lose characters.
> cli: stop alarm when cli is open

- module/scmi_perf/src/mod_scmi_perf.c
- module/thermal_mgmt/CMakeLists.txt
- module/thermal_mgmt/src/mod_thermal_mgmt.c
- module/thermal_mgmt/src/power_allocation.c
- module/thermal_mgmt/src/thermal_mgmt.h
scmi-perf: move fast channel alarm to event context
thermal-mgmt: Move power allocation to a separate file
> scmi-perf and thermal-mgmt

- product/tc1/include/clock_soc.h
- product/tc1/include/tc1_dvfs.h
- product/tc1/include/tc1_mock_psu.h
- product/tc1/include/tc1_psu.h
- product/tc1/include/tc1_timer.h
- product/tc1/scp_ramfw/config_clock.c
- product/tc1/scp_ramfw/config_css_clock.c
- product/tc1/scp_ramfw/config_dvfs.c
- product/tc1/scp_ramfw/config_gtimer.c
- product/tc1/scp_ramfw/config_mock_psu.c
- product/tc1/scp_ramfw/config_pik_clock.c
- product/tc1/scp_ramfw/config_psu.c
- product/tc1/scp_ramfw/config_scmi_perf.c
- product/tc1/scp_ramfw/config_sds.c
- product/tc1/scp_ramfw/config_system_pll.c
- product/tc1/scp_romfw/config_clock.c
- product/tc1/scp_romfw/config_cmn_booker.c
- product/tc1/scp_romfw/config_css_clock.c
- product/tc1/scp_romfw/config_gtimer.c
- product/tc1/scp_romfw/config_pik_clock.c
- product/tc1/scp_romfw/config_sds.c
- product/tc1/scp_romfw/config_system_pll.c
Internal IP are updated with their public IP names.
Signed-off-by: Rupinderjit Singh <rupinderjit.singh@arm.com>
Change-Id: I1f60bdd89207ee56d2a08c83fea3c025d8422c50
> TC1: update internal IP names of the cores to their public IP names

- module/cmn700/include/mod_cmn700.h
- module/cmn700/src/cmn700_ccg.c
- module/cmn700/src/cmn700_ccg.h
- product/rdn2/scp_ramfw/config_cmn700.c
This pull add support for ULL to ULL mode and fixes RAID to LDID programming. In addition to that cross chip mesh for the RD-N2 multichip variant.
> CMN700: CCG: add ULL to ULL support and fix RAID to LDID programming

- unit_test/user_guide.md
- user_guide.md
This set of patches updates user_guide.md and unit_test/user_guide.md
> doc: Updates userguide and minor cosmetic improvements

- product/optee-fvp/fw/config_dvfs.c
Fix a wong gpu perf level.
scmi compliance test reported error.
> product/optee-fvp: fix gpu perf level

- module/scmi_perf/src/mod_scmi_perf.c
This patch adds a log message when multiple fast channels events are pending to be processed. This will allow to identify issues related with the processing time of performance plugins when they are configured.
It is also increased the log level from `TRACE` to `ERROR` when it is not possible to create a fast channels process event.
Change-Id: I154735381342a363c101209122c15c5e562983b0
> scmi_perf: add logs when multiple fast channels events are queued

- doc/security.md
A security.md file has been added to add details of the SCP-firmware security process.
Signed-off-by: Katherine Vincent <katherine.vincent@arm.com>
Change-Id: Ia7c4d9e50e85ebc6844e255730a6e6a9d0721aca
> doc: Add security.md file.

- Gemfile.lock
chef-utils, mixlib-config and tomlrb are updated as result of latest "bundle update".
Change-Id: Ia6cef2328429c7cc79c05b2f740a9b25bc0a01ea
> Gemfile: Update file

- module/scmi_perf/src/mod_scmi_perf.c
- module/scmi_perf/src/perf_plugins_handler.c
- module/scmi_perf/test/CMakeLists.txt
- module/scmi_perf/test/config_scmi_perf.h
- module/scmi_perf/test/mod_scmi_perf_unit_test.c
This PR brings a couple of fixes and initial unit-testing for the plugins-handler extension.
> SCMI-Perf: Fixes and Unit testing

- module/scmi_clock/src/mod_scmi_clock.c
This patchset:
- cleans up the policy functions from the `scmi_clock` module. As seen in `c49f043`, due to the code complexity of the function can potentially introduce defects that can be difficult to spot and maintain. Refactoring `mod_scmi_clock_config_set_policy` function also helps to reduce the number of function calls and processing time, which can improve performance and efficiency.
Furthermore, this commit refactors the module by removing all unnecessary parameters in helper functions.
In addition, removing the FWK_WEAK to enforce the current policy until further requirements.
- Return the SCMI agent's state instead of the physical state.
The current method of reading the clock state calls the Clock HAL directly,  which can cause inconsistencies
between what is being read by …
> scmi_clock: clean up policy functions and return the SCMI agent's state instead of the physical state 

- CMakeLists.txt
- change_log.md
- framework/test/CMakeLists.txt
- readme.md
Update the change log to summarize the changes included in this release.
> Release notes for SCP-firmware v2.12

- unit_test/user_guide.md
A specific section is introduced to explain better what the expectations are from contributors with regards to unit testing.
In particular, it's worth noting that we are still in an introductory phase and, although we encourage contributors to play & add with UT, we feel that it's fair to give everybody some time to get familiar with the tool and the way it's used within the project.
> ut/user_guide: Clarify requirements for contributors

- product/n1sdp/module/n1sdp_pcie/src/pcie_enumeration.c
The exception_handler function expects the stack to be setup with the core registers in a certain order by the parent caller function (arch_exception_invalid). For release builds, as part of the optimisations, the compiler inlines the exception_handler function within the caller - arch_exception_invalid function. But this is not true of debug builds, and where because of the explicit function call, the lr is pushed onto the stack. This changes the order of registers on the stack and defies what is expected by the callee (exception_handler).
This change gets rids of the exception_handler function, moves the handling within the callee into the caller in order to do away with an explicit function call, and retain the expected order of registers pushed on to the stack.
Change-Id: …
> n1sdp: Remove exception_handler function from pcie_enumeration.c

- module/scmi_clock/test/mod_scmi_clock_unit_test.c
Increase test coverage by adding tests for invalid cases
- test passing invalid message id to scmi_clock_message_handler expected response SCMI_NOT_FOUND
- test passing incorrect payload size to scmi_clock_message_handler expected response SCMI_PROTOCOL_ERROR
> scmi_clock/test: Add tests of invalid cases to clock rate set UT

- module/dvfs/test/CMakeLists.txt
- module/dvfs/test/fwk_module_idx.h
- module/dvfs/test/mod_dvfs_unit_test.c
- unit_test/CMakeLists.txt
Add unit tests for function helpers of dvfs.
Change-Id: I7285d13fd77732e7f7658ee2e8db7bc1897dd027
> dvfs: Add initial Unit Test

- user_guide.md
A change to make some corrections to the user guide document, and update some documentation.
Change-Id: I69e760fad816a89dbeba2d876c5857d88fd645d6
> doc: Update user_guide.md

- maintainers.md
This change added Abhishek R(abhishek.rawat@arm.com) and Wen Ping Teh(WenPing.Teh@arm.com) to Core Maintainers list.
> maintainers: Update maintainer list with two new maintainers

- CMakeLists.txt
- change_log.md
- framework/test/CMakeLists.txt
- readme.md
Update the change log to summarize the changes included in this release.
> Release notes for SCP-firmware v2.13

- module/power_domain/src/mod_power_domain.c
Upon receiving a `PD_EVENT_IDX_SYSTEM_SHUTDOWN` event, `check_and_notify_system_shutdown()` checks for subscribers to the `MOD_PD_NOTIFICATION_IDX_PRE_SHUTDOWN` notification and notifies them. If there are subscribers, the `is_delayed_response` flag of the `PD_EVENT_IDX_SYSTEM_SHUTDOWN` event is set in order to wait for the subscribers answer. However, this message does not require an answer as the `response_requested` field of this event is never set.
Check that:
- The `response_requested` flag is set in the `event` input parameter in order to only answer if a response was requested.
- `mod_pd_ctx.system_shutdown.cookie` was set if a delayed answer is expected. The cookie and the `ongoing` are then reset.
> module/power_domain: Only respond to `SYSTEM_SHUTDOWN` if necessary

- .github/CODEOWNERS
Change-Id: I72de1508b656c378c8c6bf8132b89c234e0a173b
> scp: Update list of maintainers for SCP-firmware

- framework/src/assert.c
Allow overriding __assert_func for custom assert behaviour.
> assert: Add FWK_WEAK to __assert_func().

- .armv6m.cppcheck.cfg
- arch/arm/arm-m/CMakeLists.txt
- arch/arm/arm-m/src/arch_main.c
- arch/arm/arm-m/src/arch_nvic.c
- cmake/Toolchain/GNU-Baremetal.cmake
Change-Id: I7e5d13af6574a3d0466e81aa7b548df24f9871b9
> arch: add cortex-m0plus support

- tools/check_copyright.py
Files that are moved from one directory into another with 100% similarity should be excluded from the copyright check, in other words, they should not need an updated copyright year.
Add a new git operation and introduce a further comparison for files that are simply moved across directories to be excluded from the copyright check in the loop.
Change-Id: Ia9f4ece2d467eee61fc6a6afd8a07ba8339d54c6
> check_copyright: Exclude moved files from checks
